#!/usr/bin/env python3
"""An `OP_XMS` part really goes ABOVE 1MB (SPEC.md 20.12.4).

    make mseg && python3 tests/msegxms.py

MSEG's part 5 is an ASSET with `OP_XMS`. Everywhere else in this suite it
comes back as a conventional claim inside the carve, because every MartyPC
machine is an 8088 and an 8088 has nothing above linear 0x0FFFFF - so those
rows prove the FALLBACK, which is what makes `OP_XMS` a hint rather than a
mode. THIS row is the other half.

WHY QEMU: docs/TESTING.md's closed list, entry 6's shape - MartyPC cannot host
extended memory at all, so there is no "prefer MartyPC" to weigh. It is the
same reason tests/xmcheck.py is here, and this borrows its boot and its
block-table reader.

FOUR THINGS, and the last is what makes the first three mean anything:

  1. `op_seg` answers ZERO for part 5 and `op_lin` answers a non-zero linear
     base - which is the standard saying "it is up there", and is a different
     answer from the one every 8088 row gets;
  2. MSEG says `MSEG 6/6 OK`, which means it brought the part back down
     through `OSAPI_XMEM_COPY` into its own scratch part and the ROTATING sum
     matched the figure the assembler computed over the same generated bytes.
     A staging loop that dropped a chunk, doubled one or copied them out of
     order fails here, and a plain sum would not have noticed the last;
  3. MSEG's own `ms_xwhere` says 'X' rather than 'C', so the package took the
     extended path and not the fallback - the sum alone cannot tell them
     apart, because the bytes are the same bytes either way;
  4. and the block is OWNED BY THE INSTANCE, not by the kernel. That is
     SPEC.md 41.5.1's trap: `xm_alloc` attributes through `inst_caller`, and a
     claim made outside an instance's stamp bracket comes back `XM_OWN_KERN`
     and is stranded for the session - invisible, because a block nobody frees
     looks exactly like a block nobody claimed. The loader already brackets
     the ENTRY CALL with the instance's stamp, which is why this works with no
     kernel change at all; this assertion is what says so.

VERIFIED TO FAIL, which is the only thing that makes a green run mean
anything: with `op_load` made to believe there is no store, the window title
STILL SAYS `MSEG 6/6 OK` - the fallback loads the same bytes - and three of
the four assertions above fire.

IT CAUGHT TWO DEFECTS ON ITS FIRST GREEN RUN, and both are invisible on every
other row in this family because every other row runs on an 8088:

  * `op_xload` walked `op_xlin` as its copy cursor and put it back at the end
    by subtracting the BLOCK's size, where the cursor had advanced by the
    SPAN's - so every part came out `(block - span)` bytes low (the bytes
    really were at 0x110000 and `op_lin` answered 0x10FE00), and the failure
    path handed `OSAPI_XMEM_FREE` an address that was never claimed;
  * MSEG itself passed the copy DIRECTION in DI, which is also its part-loop
    counter, so part 5 set the loop back to 1 and `ms_check` never returned.
    The symptom was no window at all and `ld_status` still reading its boot
    value - which reads exactly like the loader refusing the file.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, HERE)
import xmcheck                                              # noqa: E402
import dispcp                                               # noqa: E402
import os88geom                                             # noqa: E402
import os88parts                                            # noqa: E402
import os88fixture                                          # noqa: E402
sys.path.insert(0, os.path.join(HERE, "multiseg"))
import msegsym                                              # noqa: E402
import os88qemu                                              # noqa: E402

IMG = os.path.join(ROOT, "build", "mseg.img")
O88 = os.path.join(ROOT, "build", "mseg.o88")
PKG = "MSEG.O88"
XMS_PART = 5                        # a SEMANTIC index and not derivable; the
                                    # count below is, and is read out of the
                                    # package's own part table rather than
                                    # written down (tools/os88parts.py)


def _parts():
    blob = open(O88, "rb").read()
    return len(os88parts.rows(blob[:blob[8] | (blob[9] << 8)]))
fails = []


def say(s):
    print("  " + s)


def u16(b, i=0):
    return b[i] | (b[i + 1] << 8)


def boot():
    """xmcheck's boot, with MSEG's disk in B: instead of xmtest's."""
    import time
    if os.path.exists(xmcheck.PID):
        try:
            os.kill(int(open(xmcheck.PID).read().strip()), 15)
            time.sleep(1.0)
        except (OSError, ValueError):
            pass
    for f in (xmcheck.SOCK, xmcheck.PID):
        if os.path.exists(f):
            os.remove(f)
    # `make test` DAEMONISES the emulator, so it outlives this script
    # unless somebody kills it - and the somebody is us (os88qemu).
    os88qemu.own()
    r = subprocess.run(["make", "test", "TESTAPPS=" + IMG],
                       capture_output=True, text=True, cwd=ROOT)
    if r.returncode:
        raise SystemExit("msegxms: make test failed:\n" + r.stdout + r.stderr)
    for _ in range(150):
        if os.path.exists(xmcheck.SOCK):
            break
        time.sleep(0.2)
    else:
        raise SystemExit("msegxms: QEMU never opened " + xmcheck.SOCK)
    time.sleep(12)
    return xmcheck.SOCK


class Mem(object):
    """dispcp's reader, over QMP.

    dispcp is written against MartyPC's connection object - anything with
    `.read(addr, n)` and a symbol resolver - so the QEMU rows get its listing
    and its row geometry for the cost of this shim, rather than a second copy
    of either.
    """

    def __init__(self, sock):
        self.sock = sock

    def read(self, addr, n):
        return bytes(xmcheck.read_bytes(self.sock, addr, n))


def open_pkg(sock, m):
    """Double-click MSEG.O88 in the Disk window, wherever it is drawn.

    **NOT A HARD-CODED ROW.** This row was written with xmcheck's own
    `ROW = (180, 128)`, borrowed along with its boot - and that constant was
    computed for the window xmcheck's own fixture opens, while MSEG's opens
    at (103,80). It landed on a row that SELECTED the file and did not open
    it, and what the gate then reported was "no MSEG window - the launch did
    not land", which is what a broken loader looks like. The window's own rect
    is read out of `wm_wins` and dispcp turns the NAME into the row, which is
    tests/dispcp.py's `open_named` discipline arrived at the same way.

    `row_of` answers a DIRECTORY entry and this clicks it as a visible row,
    which is only sound because build/mseg.img holds two files and cannot
    scroll. If it ever holds enough to, `dispcp.scroll_to` is what turns the
    one into the other - and it needs the keyboard, which this file's QMP
    driver does not have yet.
    """
    import time
    slots = dispcp.win_list(m, xmcheck.sym)
    if not slots:
        raise SystemExit("msegxms: drive B: opened no window")
    wx, wy, _, _ = dispcp.win_rect(m, xmcheck.sym, slots[-1])
    rows = dispcp.listing(m, xmcheck.sym)
    say("Disk window at (%d,%d), listing %r" % (wx, wy, [r[0] for r in rows]))
    row = dispcp.row_of(m, xmcheck.sym, PKG)
    x, y = dispcp.row_xy(wx, wy, row)
    say("%s is row %d, at (%d,%d)" % (PKG, row, x, y))
    xmcheck.dblclick(sock, x, y)
    time.sleep(9)


def run(sock):
    import time
    base = xmcheck.table_base(sock)
    m = Mem(sock)

    # xmcheck's own wait, and it is not generous: QEMU boots fast and then
    # reads a floppy at the speed of a floppy.
    xmcheck.dblclick(sock, *xmcheck.DISKB)
    time.sleep(7)
    open_pkg(sock, m)

    st = xmcheck.read_bytes(sock, xmcheck.sym("ld_status"), 1)[0]
    say("ld_status = %d" % st)
    if st != 0:
        raise SystemExit("msegxms: MSEG did not load (ld_status %d) - nothing "
                         "below can be asked. 4 means op_load refused itself, "
                         "which on a machine WITH a store means the XMS path "
                         "failed where the fallback path works" % st)

    wins = bytes(xmcheck.read_bytes(sock, xmcheck.sym("wm_wins"),
                                    os88geom.MAX_WIN * os88geom.WIN_SIZE))
    seg = title = None
    for i in range(os88geom.MAX_WIN):
        r = wins[i * os88geom.WIN_SIZE:(i + 1) * os88geom.WIN_SIZE]
        w = u16(r, os88geom.W_SEG)
        if not w:
            continue
        t = u16(r, os88geom.W_TITLE)
        txt = bytes(xmcheck.read_bytes(sock, (w << 4) + t, 24)).split(b"\0")[0]
        say("window %d: seg %04X title %r" % (i, w, txt))
        if txt.startswith(b"MSEG") and not txt.startswith(b"MSEGBIG"):
            seg, title = w, txt.decode("ascii", "replace")
    if seg is None:
        raise SystemExit("msegxms: no MSEG window - the launch did not land")

    say("verdict %r" % title)

    # --- 1. the standard's own answer: no segment, a linear base -----------
    # Through tests/multiseg/msegsym.py, which reads NASM'S MAP of the
    # fixture: MSEG's bss is an equ chain, and recomputing it here was the
    # same layout typed out a second time with the part count in it.
    parts = _parts()
    ms_seg = msegsym.sym("ms_seg")
    pseg = u16(bytes(xmcheck.read_bytes(sock, (seg << 4) + ms_seg
                                        + XMS_PART * 2, 2)))
    xwhere = bytes(xmcheck.read_bytes(
        sock, (seg << 4) + msegsym.sym("ms_xwhere"), 1))
    say("part %d: op_seg %04X, ms_xwhere %r" % (XMS_PART, pseg, xwhere))
    if pseg:
        fails.append(
            "part %d came back as segment %04X. On a machine WITH a store the "
            "standard must put it above 1MB, and op_seg must answer zero for "
            "it - a segment here is the conventional FALLBACK, which is the "
            "answer every 8088 row already gets (SPEC.md 20.12.4)"
            % (XMS_PART, pseg))
    if xwhere != b"X":
        fails.append(
            "MSEG says it took the %r path and should say 'X'. The bytes are "
            "the same bytes either way, so the checksum alone cannot tell the "
            "extended path from the fallback - this byte is what does"
            % xwhere)

    # --- 2. and the bytes came back --------------------------------------
    want = "MSEG %d/%d OK" % (parts, parts)
    if title != want:
        fails.append(
            "MSEG says %r, wanted %r. Part %d is checked by bringing it BACK "
            "DOWN through OSAPI_XMEM_COPY and summing it with a rotating add "
            "against the figure the assembler computed over the same "
            "generated bytes - so a staging loop that dropped a chunk, "
            "doubled one or copied them out of order fails here, and the last "
            "of those would pass a plain sum" % (title, want, XMS_PART))

    # --- 3. THE OWNER, which is the silent one ----------------------------
    live = xmcheck.blocks(sock, base)
    xmcheck.show("xm_tab", live)
    if not live:
        fails.append(
            "xm_tab is empty: nothing was ever claimed above 1MB, so the "
            "linear base above is the only evidence and it disagrees with the "
            "table")
    elif not any(own != xmcheck.XM_OWN_KERN for _, _, _, own in live):
        fails.append(
            "no block up there is owned by an INSTANCE: %r. xm_alloc "
            "attributes through inst_caller, so a claim made outside an "
            "instance's stamp bracket comes back XM_OWN_KERN and is stranded "
            "for the session. The loader brackets the ENTRY CALL with the "
            "instance's stamp (kernel/loader.inc), which is what lets a "
            "package claim for itself with no kernel change - and this is the "
            "assertion that says so. It is silent otherwise: a block nobody "
            "frees looks exactly like a block nobody claimed (SPEC.md 41.5.1)"
            % (live,))


def main():
    # NOTHING UNDER tests/ IS BUILT BY `all` (tools/os88fixture.py), so a
    # clean tree has no build/mseg.img and the row would die in `make test`
    # naming a missing floppy - an ABSENT gate reading as a failing one. Ask
    # make for it, which is the dependency graph rather than a second copy of
    # the nasm/os88pkg/os88disk ladder.
    os88fixture.need(os.path.relpath(IMG, ROOT))
    sock = boot()
    try:
        run(sock)
    finally:
        # WE BOOTED IT, SO WE SHUT IT DOWN. A guest left running holds a write
        # lock on build/os8088.img and every QEMU row after this one dies on
        # it, naming its own image and not this test.
        try:
            xmcheck.qmp(sock, "quit")
        except Exception:
            pass
    if fails:
        print("\nmsegxms: FAIL")
        for f in fails:
            print("  " + f)
        return 1
    print("\nmsegxms: the part went above 1MB, came back byte-for-byte, and "
          "belongs to the instance - PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
