#!/usr/bin/env python3
"""A package carries its own parts, and loads them itself (SPEC.md 20.12).

    make mseg && python3 tests/multiseg.py [1440|360] [machine] [system-image]

MSEG is a v3 package with flags bit 2: its file is longer than its image, and
what is past the image is three separately assembled modules it reads for
itself through `apps/os88parts.inc`. **The kernel parses none of it** - all it
learns is that bit, and it hands the entry proc the name of the file it came
out of. docs/O88-MULTISEG-PLAN.md 1 is why the kernel-side version of this
was thrown away.

MSEG checks itself THREE INDEPENDENT WAYS PER PART and publishes the verdict
as its WINDOW TITLE - `MSEG 3/3 OK` - so this row reads a string out of the
package's own segment rather than off the glass. A segment number proves a
claim was made and NOT that it was filled:

  - the SIGNATURE the primary reads out of the part's own bytes, which says
    the standard put THESE bytes at THIS segment and needs nothing called;
  - a FAR CALL to <part>:0 answering a value only that module computes, which
    says the segment is EXECUTABLE at the offset op_seg named;
  - the module summing its own data area with a ROTATING add against the
    figure the assembler computed over the same generated bytes at build
    time. A plain sum passes on a TRANSPOSITION, which is what a misaligned
    read actually produces.

WHY BOTH GEOMETRIES, and the 360KB row is not a duplicate. A part starts on a
512-byte boundary in the FILE, and `OSAPI_FILE_READ_AT` will only start a read
on a CLUSTER boundary - 512 bytes on a 1.44MB disk, 1KB on a 360KB one, and up
to 32KB on a volume neither of these is. So on the 360KB disk the read starts
BELOW the run and `op_claim`'s head slack is what puts each part's segment
where it belongs (SPEC.md 20.12.2). At 1.44MB the slack is always zero and
that arithmetic never runs at all.
"""
import struct
import sys
sys.path.insert(0, "tools")
sys.path.insert(0, "tests")
import os88marty
import os88mouse
import os88sym
import os88geom
import os88parts
import dispcp
sys.path.insert(0, "tests/multiseg")
import msegsym

def _image_of(rel):
    """A packed .o88's IMAGE bytes - the part table lives inside it.

    Relative, like every other path in this file: the row runs from the repo
    root, which is where `make` put the fixture.
    """
    blob = open(rel, "rb").read()
    return blob[:blob[8] | (blob[9] << 8)]


GEOM = sys.argv[1] if len(sys.argv) > 1 else "1440"
if GEOM not in ("1440", "360"):
    sys.exit("multiseg: geometry must be 1440 or 360")

# THE 1.44MB GEOMETRY NEEDS THE 1.44MB MACHINE, and that is not a detail:
# every other MartyPC machine here takes `pcxt_2_360k_floppies`, so a 1.44MB
# image in B: is media the drive cannot read.
DEFAULT_MACHINE = {"1440": "os8088_5150_herc_gla_144"}.get(
    GEOM, "os8088_5150_cga_gla")
MACHINE = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_MACHINE
SYS_IMG = sys.argv[3] if len(sys.argv) > 3 else "build/os8088-360.img"
APPS_IMG = "build/mseg.img" if GEOM == "1440" else "build/mseg360.img"
S = os88sym.linear
# HOW MANY PARTS IS THE PACKAGE'S OWN ANSWER, read out of the .o88's part
# table (tools/os88parts.py). It was written down here as `PARTS = 6` and wave
# 5 made it 7; the semantic indices below are not derivable and stay, but the
# COUNT and the verdict string that quotes it now follow the fixture.
PARTS = len(os88parts.rows(_image_of("build/mseg.o88")))
SCRATCH, OPT, XMS, LAZY = 3, 4, 5, 6
fails = []


def say(s):
    print("  " + s)


with os88marty.launch(SYS_IMG, apps=APPS_IMG, machine=MACHINE) as m:
    mo = os88mouse.Mouse(marty=m)
    dispcp.open_drive(m, mo, S, os88marty.settle, "B")
    wx, wy = dispcp.win_rect(m, S, dispcp.win_list(m, S)[-1])[:2]
    rows = dispcp.listing(m, S)
    if not any(n.upper() == "MSEG.O88" for n, _ in rows):
        sys.exit("multiseg: MSEG.O88 is not on %s - run `make mseg`. It lists "
                 "%r" % (APPS_IMG, [n for n, _ in rows]))

    # THE TYPE WORD FIRST. MSEG's file is bigger than its image and, on a
    # bigger fixture, could be bigger than 64KB - so the mount has to have
    # typed it 1 for anything below to be reachable at all (SPEC.md 19.1).
    have = {n.upper(): t for n, t in rows}
    say("MSEG.O88 types %d (want 1)" % have["MSEG.O88"])
    if have["MSEG.O88"] != 1:
        fails.append("the mount typed MSEG.O88 %d, not 1 - it is not "
                     "launchable, and nothing below ran" % have["MSEG.O88"])

    before = dispcp.win_list(m, S)
    dispcp.open_named(m, mo, S, os88marty.settle, wx, wy, "MSEG.O88")
    os88marty.settle(m)
    status = m.read(S("ld_status"), 1)[0]
    after = dispcp.win_list(m, S)
    say("%s: ld_status = %d, windows %r -> %r" % (GEOM, status, before, after))

    # THE LOAD FIRST, because everything below reads the window it created.
    # ld_status 4 is LD_EABORT - the entry proc returned CF=1, which is how
    # op_load refuses, and it will already have said why in a toast.
    if status != 0 or len(after) <= len(before):
        sys.exit("multiseg: MSEG did not load (ld_status %d). 2 = Bad "
                 "package, so ld_check_hdr refused image < file even with "
                 "flags bit 2; 3 = Too large; 4 = the entry proc refused, so "
                 "op_load could not size, claim or read its parts (SPEC.md "
                 "20.12)" % status)

    slot = after[-1]
    rec = m.read(S("wm_wins") + slot * dispcp.WIN_SIZE, dispcp.WIN_SIZE)
    seg = struct.unpack_from("<H", rec, os88geom.W_SEG)[0]
    toff = struct.unpack_from("<H", rec, os88geom.W_TITLE)[0]
    title = m.read((seg << 4) + toff, 24).split(b"\0")[0].decode("ascii",
                                                                "replace")
    hdr = m.read(seg << 4, 32)
    ver, flags, image = hdr[2], hdr[3], struct.unpack_from("<H", hdr, 8)[0]
    say("version %d, flags 0x%02X, image %d, verdict %r"
        % (ver, flags, image, title))

    if ver != 3:
        fails.append("MSEG loaded with version %d, not 3. THERE IS NO .o88 "
                     "v6: a package carrying parts is a v3 package with one "
                     "flag bit, for SPEC.md 54.6's reason (SPEC.md 20.12)"
                     % ver)
    if not flags & 4:
        fails.append("MSEG's flags are 0x%02X and bit 2 is clear - so the "
                     "kernel was never told its file is longer than its "
                     "image, and ld_check_hdr should have refused it"
                     % flags)

    want = "MSEG %d/%d OK" % (PARTS, PARTS)
    if title != want:
        bad = struct.unpack_from(
            "<H", m.read((seg << 4) + msegsym.sym("ms_bad"), 2), 0)[0]
        fails.append(
            "MSEG says %r, wanted %r - the parts that did NOT pass are %r. "
            "Each part is checked three independent "
            "ways - the signature the primary reads for itself, a far call "
            "answering a value only that module computes, and a rotating sum "
            "against the figure the assembler computed at build time - so a "
            "wrong base, an unexecutable segment and a short or transposed "
            "read are three different failures and this is one of them "
            "(SPEC.md 20.12)"
            % (title, want, [i for i in range(PARTS) if bad & (1 << i)]))

    # ...and the segments the standard handed out, which is the loader's half
    # of the same question: the title is MSEG's opinion, these are addresses.
    segs = []
    # THROUGH tests/multiseg/msegsym.py, which reads NASM'S MAP of the fixture
    # and refuses a map that is not byte-identical to the .bin that shipped.
    # This was `image + OP_BSS + PARTS*2 + ...` - MSEG's own bss chain typed
    # out a second time, in Python, with the part count in it - and the
    # namespace one along has already gone stale exactly that way (see
    # tools/os88parts.py's header).
    ms_seg = msegsym.sym("ms_seg")

    # THE HEAD SLACK, and this is what makes the two geometries different
    # rows rather than one run twice. A part begins on a 512-byte boundary in
    # the FILE; a read may only begin on a CLUSTER boundary, which is 512
    # bytes here and 1KB on the 360KB disk. MSEG's image is padded to three
    # sectors so its first part lands at 1,536 - 512 past a 1KB cluster - so
    # the 360KB read starts BELOW the run and op_seg has to add the slack
    # back. Unpadded it was 1,024, aligned on both, and this row passed
    # without ever running the arithmetic it exists for (SPEC.md 20.12.2).
    slack = struct.unpack_from(
        "<H", m.read((seg << 4) + msegsym.sym("op_slack"), 2), 0)[0]
    want_slack = 512 if GEOM == "360" else 0
    say("op_slack = %d (want %d on a %s disk)" % (slack, want_slack, GEOM))
    if slack != want_slack:
        fails.append(
            "the head slack is %d and should be %d. At 1440 the cluster is "
            "512 bytes and a 512-aligned part is always cluster-aligned too, "
            "so the slack is zero and the arithmetic never runs; at 360 the "
            "cluster is 1KB and MSEG's three-sector image puts its first "
            "part 512 past one. A zero here at 360 means this row is passing "
            "without testing what it is for (SPEC.md 20.12.2)"
            % (slack, want_slack))
    for i in range(PARTS):
        v = struct.unpack_from("<H", m.read((seg << 4) + ms_seg + i * 2, 2), 0)[0]
        sig = m.read((v << 4) + 2, 4) if v and i < SCRATCH else b"----"
        segs.append(v)
        say("  part %d  seg %04X  sig %r" % (i, v, sig))
        if not v and i not in (OPT, LAZY):
            fails.append("part %d has no segment: op_load claimed nothing for "
                         "it, or op_seg cannot find it" % i)
    if segs[LAZY]:
        fails.append(
            "part %d is OP_LAZY and it has a segment (%04X) after the LAUNCH. "
            "op_size steps over a lazy row: not claimed, not read, and "
            "op_seg answering 0 until the package calls op_fetch. "
            "tests/mseglazy.py is the row that drives that whole cycle; this "
            "one only says it did not happen by itself (SPEC.md 20.12.4)"
            % (LAZY, segs[LAZY]))
    if segs[OPT]:
        fails.append(
            "part %d is 600KB and OPTIONAL and it was GRANTED (segment %04X). "
            "A machine that can spare it is one where this row proves "
            "nothing, which is why the size is absurd rather than merely "
            "large (SPEC.md 47)" % (OPT, segs[OPT]))
    live = [v for v in segs if v]
    if len(set(live)) != len(live):
        fails.append("two parts share a base segment %r - the run's or the "
                     "scratch area's arithmetic collapsed them (SPEC.md "
                     "20.12.2)" % (segs,))
    if segs[SCRATCH] and segs[SCRATCH] < max(segs[:SCRATCH]):
        fails.append(
            "the scratch part landed at %04X, below the filed parts %r. It "
            "belongs AFTER the carved run in the one claim - op_runkb is the "
            "offset that puts it there (SPEC.md 20.12.4)"
            % (segs[SCRATCH], segs[:SCRATCH]))

if fails:
    print("\nmultiseg: FAIL on %s" % GEOM)
    for f in fails:
        print("  " + f)
    sys.exit(1)
print("\nmultiseg: three parts in one file, sized with no disk read, claimed "
      "once and read by the PACKAGE - PASS on %s (%s)" % (GEOM, MACHINE))
