; =============================================================================
; os8088 - tests/multiseg/mseg.asm
;
; MSEG - the consumer that proves apps/os88parts.inc (SPEC.md 20.12). A TEST
; package: `make mseg` builds it and no shipped floppy carries it, like
; tests/wire (SPEC.md 78.9).
;
; THREE PARTS, and three independent checks on each of them, because a segment
; number on the screen proves a claim was made and NOT that it was filled:
;
;   - the SIGNATURE the primary reads out of the part's own bytes, which says
;     the standard put THESE bytes at THIS segment and needs nothing called;
;   - a FAR CALL to <part>:0 answering a value only that module computes,
;     which says the segment is executable at the offset op_seg named;
;   - the module summing its own data area with a ROTATING add against the
;     figure the assembler computed over the same generated bytes. A plain sum
;     passes on a transposition, which is what a misaligned read produces.
;
; THE VERDICT IS THE WINDOW TITLE, so the host reads a string out of the
; package's own segment rather than off the glass - `MSEG 3/3 OK`.
;
; The checks run in the ENTRY PROC, before the window is ever painted, for the
; reason the whole design turns on: by then op_load has claimed and read
; everything, so this is the earliest moment the answer exists - and an entry
; proc may not draw, which is exactly what makes it the right place to decide
; rather than to display.
; =============================================================================

%include "os88api.inc"

    OS88_HEADER 'MSEG', ms_entry, OS88_F_PARTS

%include "os88parts.inc"

MS_PARTS   equ 7
MS_SCRATCH equ 3                    ; ...and part 3 is zero-filled scratch
MS_OPT     equ 4                    ; ...part 4 must be REFUSED
MS_XMS     equ 5                    ; ...part 5 may be above 1MB, or not
MS_LAZY    equ 6                    ; ...and part 6 is not here at all until
                                    ;    somebody presses a key
MS_SCR_KB  equ 8
MS_OPT_KB  equ 600                  ; chosen so NOTHING here can grant it: a
                                    ; 640KB XT has about 500KB of heap. A part
                                    ; that might or might not be refused would
                                    ; make this row report the MACHINE rather
                                    ; than the mechanism

    OS88_PARTS_BEGIN MS_PARTS
      OS88_PART OP_SEG                  ; 0 code
      OS88_PART OP_SEG                  ; 1 code
      OS88_PART OP_ASSET                ; 2 data - and `kind` changes NOTHING
                                        ;   about how it is claimed or read
                                        ;   here, which is deliberate: it is
                                        ;   the package's own note about what
                                        ;   it means to do with the part
      OS88_PART OP_ASSET, OP_ZERO, MS_SCR_KB
                                        ; 3 8KB, zeroed, NO FILE BYTES AT ALL -
                                        ;   so it costs no disk, and it is
                                        ;   refused BEFORE a sector is read
                                        ;   rather than after
      OS88_PART OP_ASSET, OP_ZERO | OP_OPT, MS_OPT_KB
                                        ; 4 600KB and OPTIONAL: it must be
                                        ;   refused, and the launch must carry
                                        ;   on without it (SPEC.md 47)
      OS88_PART OP_ASSET, OP_XMS        ; 5 above 1MB IF THIS MACHINE HAS ANY,
                                        ;   and an ordinary filed part inside
                                        ;   the carve if not - which is every
                                        ;   8088, and therefore every MartyPC
                                        ;   machine here (SPEC.md 41). It is
                                        ;   LAST among the EAGER filed parts
                                        ;   because os88pkg.py requires it:
                                        ;   the span that goes up has to be
                                        ;   contiguous
      OS88_PART OP_SEG, OP_LAZY         ; 6 NOT CLAIMED AND NOT READ AT LOAD.
                                        ;   op_size steps over its row, so it
                                        ;   is in no total and outside the
                                        ;   carve, and op_fetch claims and
                                        ;   reads it when ms_onkey asks. It is
                                        ;   the LAST row because a lazy part
                                        ;   in the middle of the run would be
                                        ;   read by the one read the carve
                                        ;   exists to be - which os88pkg.py
                                        ;   also refuses
    OS88_PARTS_END

; --- the part module's ABI (tests/multiseg/msegpart.inc) ---------------------
MP_SIG     equ 2                    ; 'MSG'
MP_IDX     equ 5                    ; the part's index
MP_SUM     equ 6                    ; word: the sum its data area must have
MP_DLO     equ 8                    ; word: where that area starts
MP_DHI     equ 10                   ; ...and ends

MS_CONT_W  equ 302                  ; content width:  304 outer - 2px borders
MS_ROW_H   equ 10

; -----------------------------------------------------------------------------
; ms_entry - package entry (SPEC.md 20.2)
; in:  DS = CS = our segment, ES = KERNEL_SEG, SI = the name of the file we
;      came out of, gfx lock NOT held
; out: BX = window ptr, CF clear
;
; op_load IS THE FIRST THING CALLED and that is a rule, not a habit: SI holds
; an offset into the KERNEL's segment at a buffer the loader reuses on the
; next launch, so nothing later can recover it (SPEC.md 20.2).
; -----------------------------------------------------------------------------
ms_entry:
    push cx
    push dx
    push di
    call op_load                    ; CF=1: it has already said why
    jc .refuse
    call ms_check                   ; fills ms_ok / ms_seg / the title
    mov si, ms_tpl
    call OSAPI_WM_CREATE            ; BX = window ptr, CF on table full
    jmp short .out
.refuse:
    stc                             ; ...and the loader tears down what exists
.out:
    pop di
    pop dx
    pop cx
    ret

; -----------------------------------------------------------------------------
; ms_check - the three checks, on every part
; in:  nothing; op_load has returned CF=0
; out: nothing; [ms_ok] = parts that passed all three, the title rewritten
; clobbers: everything but the caller's saved set
; -----------------------------------------------------------------------------
ms_check:
    mov byte [ms_ok], 0
    mov byte [ms_last], 0
    mov word [ms_bad], 0
    xor di, di                      ; DI = part index
.part:
    mov ax, di
    call op_seg                     ; AX = its base segment, 0 = not there
    mov bx, di
    shl bx, 1
    mov [ms_seg + bx], ax           ; banked for the paint, whatever it is
    cmp di, MS_SCRATCH
    je .scratch
    cmp di, MS_OPT
    je .opt
    cmp di, MS_XMS
    je .xms
    cmp di, MS_LAZY
    je .lazy
    or ax, ax
    jz .nx
    call ms_modchk
    jc .nx
    inc byte [ms_ok]
.nx:
    jmp .next

    ; --- part 3: scratch, and it cost no disk at all ------------------------
    ; EVERY byte zero AND the claim writable to its last one - a claim short of
    ; what was asked reads back as zeros just as convincingly as a correct one,
    ; so the write is the half that says the size was real.
.scratch:
    or ax, ax
    jz .snx
    mov es, ax
    xor si, si
    mov cx, MS_SCR_KB * 512         ; words
.zsee:
    cmp word [es:si], 0
    jne .snx
    add si, 2
    loop .zsee
    mov word [es:MS_SCR_KB * 1024 - 2], 0x5A5A
    cmp word [es:MS_SCR_KB * 1024 - 2], 0x5A5A
    jne .snx
    mov word [es:MS_SCR_KB * 1024 - 2], 0    ; ...AND PUT BACK. ms_check runs
                                             ; again on every ms_onkey now, and
                                             ; the zero scan above would find
                                             ; this probe on the second pass -
                                             ; a check that fails because the
                                             ; last run of the same check wrote
                                             ; to what it was checking
    inc byte [ms_ok]
.snx:
    jmp .next

    ; --- part 5: the XMS-accepting asset, WHEREVER IT LANDED ----------------
    ; A hint, not a mode (SPEC.md 20.12.4): a segment means the store refused
    ; and it is ordinary memory, which every 8088 gets; no segment with a
    ; linear base means it is above 1MB and the only way to look at it is to
    ; bring it back down. THE SAME THREE CHECKS EITHER WAY, which is the
    ; point - the bytes are the bytes wherever they were put.
.xms:
    or ax, ax
    jz .xup
    mov byte [ms_xwhere], 'C'       ; conventional: an ordinary module
    call ms_modchk
    jc .next
    inc byte [ms_ok]
    jmp .next
.xup:
    mov byte [ms_xwhere], 'X'
    mov ax, di
    call op_lin                     ; DX:AX = the 32-bit linear base
    mov bx, ax
    or bx, dx
    jz .next                        ; no segment AND no token is nothing at all
    ; Bring it down into part 3's scratch claim - the one conventional buffer
    ; big enough - and check it there. It is 8KB and the part is under 2KB.
    push dx
    push ax
    mov ax, MS_SCRATCH
    call op_seg
    pop bx                          ; ...the linear base, back off the stack
    pop dx
    or ax, ax
    jz .next
    mov [ms_xbuf], ax
    mov es, ax
    mov ax, di                      ; the LENGTH out of the part's own row, not
    call op_row                     ; a constant: a written-down 1052 would go
    mov cx, [si+OP_R_LEN]           ; stale the moment msegp3.bin changed size,
    inc cx                          ; and a short copy reads as a bad checksum
    and cl, 0xFE                    ; (OSAPI_XMEM_COPY takes even counts only)
    xor si, si
    push di                         ; DI IS THE PART INDEX and the copy's
    mov di, 1                       ; direction argument wants the same
    mov ax, bx                      ; register - unbracketed, part 5 sets the
    call OSAPI_XMEM_COPY            ; loop counter to 1 and .part runs for
    pop di                          ; ever, which is a HANG and not a failure
    jc .next
    mov es, [ms_xbuf]
    cmp byte [es:MP_SIG], 'M'
    jne .next
    cmp byte [es:MP_IDX], MS_XMS
    jne .next
    mov cx, [es:MP_DHI]             ; sum its data area HERE - the module
    sub cx, [es:MP_DLO]             ; cannot be far-called where it is
    mov si, [es:MP_DLO]
    xor ax, ax
.xsum:
    mov bl, [es:si]
    xor bh, bh
    add ax, bx
    rol ax, 1
    inc si
    loop .xsum
    cmp ax, [es:MP_SUM]
    jne .next
    inc byte [ms_ok]
    jmp .next

    ; --- part 6: LAZY, and the check is that it matches what we ASKED for ---
    ; BOTH DIRECTIONS ARE A FAILURE. Absent when nothing has fetched it is
    ; correct - that is what lazy IS - and absent after a fetch means the
    ; fetch did not work; present before one means the carve read it anyway,
    ; which is the whole thing OP_LAZY exists to stop. So the check is against
    ; [ms_want], not against presence, and a row that only ever tested
    ; `is it there` would pass on a package with no lazy mechanism at all.
.lazy:
    or ax, ax
    jz .labsent
    cmp byte [ms_want], 0
    je .lnx                     ; here when nothing asked for it
    call ms_modchk              ; ...and if it IS here it has to be the module
    jc .lnx
    inc byte [ms_ok]
    jmp .next
.labsent:
    cmp byte [ms_want], 0
    jne .lnx                    ; asked for and not here
    mov al, MS_LAZY             ; ...and the standard must AGREE it could be
    call op_lazyok              ; had, because absent is also what a broken
    jc .lnx                     ; table would answer (SPEC.md 47)
    inc byte [ms_ok]
.lnx:
    jmp .next

    ; --- part 4: OPTIONAL, and 600KB - so it MUST have been refused ---------
    ; A zero segment is op_seg saying "you cannot have it", and carrying on is
    ; what SPEC.md 47 asks of a feature that cannot be had. A machine that
    ; GRANTED it would be one where this row proves nothing, which is why the
    ; size is absurd rather than merely large - and op_optok is the byte a
    ; package greys a row from, because zero is also what a mis-declared table
    ; would answer.
.opt:
    or ax, ax
    jnz .next                       ; granted: the refusal path never ran
    cmp byte [op_optok], 0
    jne .next                       ; ...and the standard has to agree it was
    inc byte [ms_ok]                ; refused, not merely be missing
.next:
    ; WHICH PART FAILED, and not only how many. Every case above either
    ; increments [ms_ok] or does not, so the shadow says which - and a gate
    ; reading `6/7` off the title otherwise has to guess, or reproduce all
    ; three checks host-side to find out. It is a word, so it is one read.
    mov al, [ms_ok]
    cmp al, [ms_last]
    jne .passed
    push cx
    mov cx, di
    mov ax, 1
    shl ax, cl
    or [ms_bad], ax
    pop cx
.passed:
    mov al, [ms_ok]
    mov [ms_last], al
    inc di
    cmp di, MS_PARTS
    jb .part

    mov al, [ms_ok]                 ; 'MSEG n/3 OK' - the verdict the host
    add al, '0'                     ; reads out of the window record
    mov [ms_t_n], al
    mov al, 'O'
    mov ah, 'K'
    cmp byte [ms_ok], MS_PARTS
    je .say
    mov al, 'B'
    mov ah, 'A'
    mov byte [ms_t_v+2], 'D'
.say:
    mov [ms_t_v], al
    mov [ms_t_v+1], ah
    ret

; -----------------------------------------------------------------------------
; ms_modchk - one msegpart.inc module, three independent ways
; in:  DI = the part index, [ms_seg + DI*2] = the segment it landed at
; out: CF=0 it is that module and its data arrived; CF=1 one of the three said
;      otherwise
; clobbers: AX, BX, CX, ES, flags
; -----------------------------------------------------------------------------
ms_modchk:
    push di
    mov bx, di
    shl bx, 1
    mov ax, [ms_seg + bx]
    mov es, ax

    ; sig: the caller reads the part's own bytes, and nothing is called
    cmp byte [es:MP_SIG], 'M'
    jne .no
    cmp byte [es:MP_SIG+1], 'S'
    jne .no
    cmp byte [es:MP_SIG+2], 'G'
    jne .no
    mov al, [es:MP_IDX]
    xor ah, ah
    cmp ax, di
    jne .no                         ; part 1's bytes at part 0's base

    ; call: a far call to <part>:0, verb 0
    mov ax, [es:MP_SUM]
    push ax                         ; ...banked across the calls, because ES is
                                    ; the part's and the far call may not
                                    ; promise it back
    mov ax, [ms_seg + bx]
    mov [ms_fp+2], ax
    mov word [ms_fp], 0             ; the entry IS offset 0 (msegpart.inc)
    xor al, al                      ; verb 0
    call far [ms_fp]
    mov cx, 0x5300
    or cx, di
    cmp ax, cx
    jne .drop                       ; a far call into a claim the standard
                                    ; never filled cannot answer this

    ; sum: verb 1, against the assembler's own figure
    mov al, 1
    call far [ms_fp]
    pop cx                          ; the declared sum
    cmp ax, cx
    jne .no
    clc
    jmp short .out
.drop:
    pop cx
.no:
    stc
.out:
    pop di
    ret

; -----------------------------------------------------------------------------
; ms_paint - W_PAINT: one row per part, so a human sees what the host reads
; in:  SI = window ptr; caller holds the gfx lock
; out: nothing; every register preserved
; -----------------------------------------------------------------------------
ms_paint:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    mov bx, si
    call OSAPI_WM_CONTENT           ; AX = content left, DX = content top
    mov [ms_cx], ax
    mov [ms_cy], dx
    mov byte [ms_i], 0
.row:
    mov bl, [ms_i]                  ; the index is in bss and not in a
    xor bh, bh                      ; register, because ms_hex4 spends three
    mov al, bl                      ; of them and OSAPI_FONT_RUN takes four
    add al, '0'
    mov [ms_r_n], al
    shl bx, 1
    mov ax, [ms_seg + bx]
    mov di, ms_r_seg
    call ms_hex4
    mov al, [ms_i]
    xor ah, ah
    mov bx, MS_ROW_H
    mul bx
    add ax, [ms_cy]
    add ax, 4
    mov dx, ax
    mov cx, [ms_cx]
    add cx, 4
    mov si, ms_row
    mov ax, (CWHITE << 8) | CBLACK  ; an OPAQUE run: the ground and the glyphs
    call OSAPI_FONT_RUN             ; in one pass (SPEC.md 6.1)
    inc byte [ms_i]
    cmp byte [ms_i], MS_PARTS
    jb .row
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    ret

; -----------------------------------------------------------------------------
; ms_onkey - W_ONKEY: toggle the LAZY part (SPEC.md 20.12.4)
; in:  AL = ascii, AH = scan, SI = window ptr, ES = KERNEL_SEG
; out: nothing
;
; A KEY AND NOT THE ENTRY PROC, and that is the point of the row that drives
; this: a fetch inside the entry proc happens during the launch, so the
; sectors it moves are indistinguishable from the sectors the carve moved. On
; a key they are a separate measurement, and they are also what a lazy part is
; FOR - a working set that arrives when the user asks for the thing that needs
; it, and goes away again.
;
; Any key toggles. The window is redrawn by asking for it rather than by
; drawing here: a callback does not hold the gfx lock (SPEC.md 11).
; -----------------------------------------------------------------------------
ms_onkey:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push si                     ; the window, for the redraw below
    cmp byte [ms_want], 0
    jne .drop
    mov al, MS_LAZY
    call op_fetch               ; CF=1: a toast has already said why, and
    jc .done                    ; [ms_want] stays 0 so the verdict still holds
    mov byte [ms_want], 1
    mov byte [ms_lazy], 'F'
    jmp short .redraw
.drop:
    mov al, MS_LAZY
    call op_drop                ; no disk, no failure path: a claim goes back
    mov byte [ms_want], 0
    mov byte [ms_lazy], 'D'
.redraw:
    call ms_check               ; ...and the verdict again, over the new state
.done:
    pop si
    mov bx, si
    xor ax, ax                  ; 0 = "the bytes W_TITLE already names changed
    call OSAPI_WM_TITLE         ; underneath it", which is what ms_check did
    call ms_paint               ; SI is the window and the caller holds the
                                ; gfx lock, which is what a W_ONKEY is
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    ret

; -----------------------------------------------------------------------------
; ms_hex4 - AX as four hex digits at DS:DI
; in:  AX = the value, DI = where; out: DI unchanged
; clobbers: AX, BX, CX, flags
; -----------------------------------------------------------------------------
ms_hex4:
    push di
    mov bx, ax
    mov cx, 4
.d:
    mov ax, bx
    rol bx, 1
    rol bx, 1
    rol bx, 1
    rol bx, 1
    mov al, bl
    and al, 0x0F
    add al, '0'
    cmp al, '9'
    jbe .put
    add al, 7
.put:
    mov [di], al
    inc di
    loop .d
    pop di
    ret

; --- window template (SPEC.md 11: 16 bytes, 8 words) -------------------------
ms_tpl:
    dw 120, 84, 304, 94             ; x, y, w, h
    dw ms_title, ms_paint, ms_onkey, 0

ms_title:  db 'MSEG '
ms_t_n:    db '0'
           db '/7 '
ms_t_v:    db 'OK', 0, 0

ms_row:    db 'part '
ms_r_n:    db '0'
           db '  seg '
ms_r_seg:  db '0000', 0

; --- the image is padded to an ODD number of sectors, deliberately -----------
; A part starts on a 512-byte boundary in the FILE and OSAPI_FILE_READ_AT will
; only start a read on a CLUSTER boundary, which is 1KB on a 360KB disk and
; 512 bytes on a 1.44MB one. op_claim's head slack (SPEC.md 20.12.2) is what
; bridges that - and it is ZERO whenever the first part happens to land on a
; cluster anyway. Unpadded, MSEG's image was two sectors and the first part
; began at 1,024: aligned on BOTH geometries, so the arithmetic the 360KB row
; exists for never ran and the row passed without testing it.
;
; SEVEN sectors puts the first part at 3,584, which is 512 past a 1KB cluster
; (as five and three were: the rule is an ODD number of sectors).
; tests/multiseg.py asserts the slack is non-zero at 360 and zero at 1440, so
; this cannot quietly stop being true.
;
; If the code ever outgrows it, `times` goes negative and NASM says so - which
; is the right failure: somebody has to pick the next odd multiple and check
; the row still means something.
    times 3584 - ($ - $$) db 0

    OS88_BSS OP_BSS + MS_BSS
    OS88_IMAGE_END

; --- loader-zeroed bss (SPEC.md 21 step 5) -----------------------------------
; THE STANDARD'S WORDS COME FIRST (apps/os88parts.inc): it takes the first
; OP_BSS bytes off os88_image_end and ours follow, which is the convention the
; include documents and the one thing a package embedding it has to remember.
ms_seg     equ os88_image_end + OP_BSS + 0     ; our copy of each part's base
ms_fp      equ ms_seg + MS_PARTS * 2           ; a far pointer, built per call
ms_ok      equ ms_fp + 4                       ; byte: parts that behaved
ms_cx      equ ms_ok + 2                       ; the content origin, banked
ms_cy      equ ms_cx + 2                       ; once a paint
ms_i       equ ms_cy + 2                       ; ...and the row being drawn
ms_xwhere  equ ms_i + 2                        ; 'C' conventional / 'X' above
                                               ; 1MB, so the host sees WHICH
                                               ; path this machine took rather
                                               ; than inferring it
ms_xbuf    equ ms_xwhere + 2                   ; ...and where it was brought
ms_want    equ ms_xbuf + 2                      ; byte: is the LAZY part meant
                                                ; to be here? The verdict is
                                                ; against this and not against
                                                ; presence, so both directions
                                                ; are a failure
ms_lazy    equ ms_want + 2                      ; ...and what we last did to
                                                ; it: 0 nothing, 'F' fetched,
                                                ; 'D' dropped
ms_bad     equ ms_lazy + 2                      ; word: bit i set = part i did
ms_last    equ ms_bad + 2                       ; not pass, against a shadow of
                                                ; [ms_ok] one part behind
MS_BSS     equ MS_PARTS * 2 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 2 + 2 + 2 + 2
