; =============================================================================
; os8088 - apps/midirack/midirack.asm
;
; MIDIRACK.O88 - a MIDI file player (SPEC.md 105). A Standard MIDI File, type
; 0 or 1, read whole into one claim and played through whatever the machine
; has:
;
;   an OPL2 or OPL3 (an AdLib, or a Sound Blaster's own chip) - claimed whole
;       through SOUND.DRV's package verbs (SPEC.md 34.12), 8 or 17 voices of
;       two-operator FM from an original General MIDI bank (mrtab.inc);
;   a Sound Blaster's DSP - a software synth (pulse waves and noise) streamed
;       through an external ring, behind the desktop (SPEC.md 34.5.3);
;   the PC speaker - the same synth through os88spk.inc's pulse width, in a
;       rate bracket like the Audio Player's (SPEC.md 34.11, 86.21); or, with
;       "Play in Background" ticked, ONE square wave on the desktop, the
;       melody, through OSAPI_SND_TONE.
;
; Files (SPEC.md 105.2):
;   midirack.asm  header, icon, the .MID association, all bss, entry, data
;   mrseq.inc     the SMF reader and the sequencer          (prefix mrq_)
;   mrchan.inc    the sixteen channels and the voices       (mrc_, mrv_)
;   mrfm.inc      the FM chip, and the speaker's tone       (mrf_, mrn_)
;   mrsyn.inc     the synth                                  (mry_)
;   mrout.inc     the outputs opened, played, paused, closed; the worker
;                 and the speaker's bracket                  (mro_, mrw_, mrk_)
;   mrlist.inc    the playlist and the file loads           (mrl_)
;   mrui.inc      the window: layout and drawing            (mru_)
;   mrcb.inc      the callbacks, the transport, the cards   (mr_)
;   mrtab.inc     GENERATED by tools/os88midi.py: pitches, levels, names,
;                 the FM bank, the synth's voicing
; =============================================================================

%include "os88api.inc"
%include "sndpkg.inc"

    OS88_HEADER 'MIDIRack', mr_entry, OS88_F_ICON | OS88_F_ASSOC, OS88_STACK_384

; --- embedded 16x16 icon (SPEC.md 20.2): a rack unit with a keyboard --------
    OS88_ICON16
    dw 0x0000, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE
    dw 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x7FFE, 0x0000
    dw 0x0000, 0x7FFE, 0x4002, 0x5FFA, 0x5A5A, 0x5FFA, 0x4002, 0x7FFE
    dw 0x4924, 0x4924, 0x6DB6, 0x6DB6, 0x6DB6, 0x4002, 0x7FFE, 0x0000
    OS88_ICON16_END

; --- the extensions this program opens (SPEC.md 54.6, flags bit 1) ----------
    OS88_ASSOC16
    db 2
    OS88_ASSOC_EXT 'MID'
    OS88_ASSOC_EXT 'SMF'
    OS88_ASSOC16_END

; --- THE COLOUR FACE'S PICTURES (SPEC.md 105.9.5): MIDIRACK.GFX ------------
; tools/os88midart.py draws the transport's fifteen faces into a file that
; ships BESIDE the package and is read only on a colour primary - a Hercules
; or a CGA machine never spends a byte or a revolution on it, and a disk
; without it plays exactly the same with code-drawn buttons. It is a sidecar
; and not a part (SPEC.md 20.12) for one measured reason: os88pkg.py refuses
; to compress an image that has parts, and this image is 30 KB packed to 25.
; The four numbers are the generator's, which compares them (--check-asm)
MRA_W       equ 48                  ; a face: whole bytes, so BLITP takes it
MRA_H       equ 30
MRA_NB      equ 5                   ; Prev, Play, Pause, Stop, Next
MRA_NS      equ 3                   ; up, pressed, greyed
MRA_FACE    equ 4 * MRA_H * MRA_W / 8
MRA_SIZE    equ MRA_NB * MRA_NS * MRA_FACE

; =============================================================================
; the package-wide bss accumulator (the Audio Player's %assign pattern)
; =============================================================================
%assign MR_BSS 0
%macro MRB 1
%1 equ os88_image_end + MR_BSS
%assign MR_BSS MR_BSS + 1
%endmacro
%macro MRW 1
%1 equ os88_image_end + MR_BSS
%assign MR_BSS MR_BSS + 2
%endmacro
%macro MRD 1
%1 equ os88_image_end + MR_BSS
%assign MR_BSS MR_BSS + 4
%endmacro
%macro MRBUF 2
%1 equ os88_image_end + MR_BSS
%assign MR_BSS MR_BSS + (%2)
%endmacro

; --- states, outputs ---------------------------------------------------------
MR_ST_STOP  equ 0
MR_ST_PLAY  equ 1
MR_ST_PAUSE equ 2

MR_OUT_AUTO equ 0                   ; [mr_want]: the user's choice (Settings)
MR_OUT_OPL3 equ 1
MR_OUT_OPL2 equ 2
MR_OUT_SB   equ 3
MR_OUT_SPK  equ 4

MRO_NONE    equ 0                   ; [mr_out]: what is OPEN
MRO_FM      equ 1
MRO_SB      equ 2
MRO_SPK     equ 3                   ; the synth, in a bracket
MRO_TONE    equ 4                   ; one square wave, on the desktop

MR_FILEMAX  equ 63                  ; KB: the largest file taken whole

; --- shell state -------------------------------------------------------------
    MRW mr_win
    MRB mr_state                    ; MR_ST_*
    MRB mr_want                     ; MR_OUT_*
    MRB mr_out                      ; MRO_*
    MRB mr_loop                     ; Loop Playback
    MRB mr_levels                   ; Show Levels
    MRB mr_bg                       ; Play in Background (the speaker's tone)
    MRB mr_have_worker
    MRB mr_inpass                   ; the worker is mid-pass (mr_drain)
    MRB mr_seqon                    ; the sequencer may run
    MRB mr_ended                    ; the song has played out: the UI's turn
    MRB mr_dry                      ; the load's dry run: no output
    MRB mr_first_paint
    MRB mr_card                     ; the card up: 0 / MR_CARD_*
    MRB mr_arg_pending
    MRBUF mr_arg_name, 16
    MRW mr_arg_dir
    MRB mr_arg_vol
    MRW mr_msg                      ; status line 3
    MRW mr_fseg                     ; the song's claim
    MRW mr_fkb                      ; ...its size in KB
    MRW mr_fsize                    ; the song's bytes
    MRB mr_loaded                   ; a song is in the claim...
    MRB mr_lidx                     ; ...this playlist entry
    MRW mr_lenlo                    ; its length in ms (the dry run)
    MRW mr_lenhi
    MRW mr_meas                     ; its measures
    MRW mr_bpm0                     ; its first tempo, BPM
    MRBUF mr_w, 8                   ; the multi-word scratch (mr_mdiv)
    MRB mr_cpu                      ; CPU_8086 / 286 / 386
    MRB mr_fmkind                   ; 0 none / SND_OPL2 / SND_OPL3 (at entry)
    MRB mr_hassb                    ; SND_CAP_PCM_BG at entry
    MRB mr_sbhi                     ; ...and SND_CAP_PCM_HI: rates past 22 kHz
    MRB mr_rate                     ; the synth's rate: an index into mr_rates,
                                    ; 0 = Automatic (Settings, SPEC.md 105.9.2)
    MRB mr_cfgdirty                 ; a setting moved since MIDIRACK.CFG
    MRBUF mr_snap, 2                ; (scratch)

; =============================================================================
; mr_entry - the loader calls this once (SPEC.md 20.1). The loader shows the
;            window afterwards: no drawing and no worker here.
; =============================================================================
mr_entry:
    call OSAPI_CPU_INFO
    mov [mr_cpu], al
    call OSAPI_SND_CAPS             ; AX = caps
    test ax, SND_CAP_PCM_BG
    jz .nosb
    mov byte [mr_hassb], 1
.nosb:
    test ax, SND_CAP_PCM_HI
    jz .nohi
    mov byte [mr_sbhi], 1
.nohi:
    test ax, SND_CAP_FM
    jz .nofm
    mov al, SND_FM_INFO             ; which chip (claims nothing)
    call OSAPI_SND_FM
    jc .nofm
    mov [mr_fmkind], al
.nofm:
    call mra_load                   ; the colour face's pictures, if colour
    mov byte [mr_levels], 1
    mov byte [mr_want], MR_OUT_AUTO
    call OSAPI_ARG_FILE             ; CF = 1 launched empty
    jc .nodoc
    mov di, mr_arg_name             ; SI -> the name in KERNEL_SEG (ES)
    mov cx, 15
.cpn:
    mov al, [es:si]
    mov [di], al
    inc si
    inc di
    or al, al
    jz .cpd
    loop .cpn
.cpd:
    mov byte [mr_arg_name+15], 0
    mov [mr_arg_dir], dx
    mov [mr_arg_vol], bl
    mov byte [mr_arg_pending], 1
.nodoc:
    call mrl_init
    mov si, mr_tpl
    call OSAPI_WM_CREATE            ; BX = window ptr
    jc .fail
    mov [mr_win], bx
    mov si, mr_prefer               ; a shape for each of the three screens
    call OSAPI_WM_PREFER
    push ax
    push bx
    push si
    push di
    push dx
    mov ax, bx
    mov bx, mru_btrec
    mov si, mr_onup
    mov di, mr_ondrag
    mov dx, mr_onclick              ; OUR click work: the library takes the
    call os88ui_btninit             ; press first and chains here
    pop dx
    pop di
    pop si
    pop bx
    pop ax
    OS88_REGION_MOVABLE
    mov si, mr_menus
    call OSAPI_MENU_SET
    mov si, mr_about
    call OSAPI_ABOUT_SET
    mov ax, mr_onwake
    call OSAPI_WM_ONWAKE
    mov ax, mr_onclose
    call OSAPI_WM_ONCLOSE
    mov word [mr_msg], mr_s_ready
    mov byte [mr_state], MR_ST_STOP
    mov byte [mr_first_paint], 1    ; the settled repaint, and the playlist,
    mov bx, [mr_win]                ; from the first wake (SPEC.md 86.7)
    call OSAPI_WM_WAKE
    clc
    ret
.fail:
    call mra_free                   ; (a claim taken before the window was)
    stc
    ret

; =============================================================================
%include "mrseq.inc"
%include "mrchan.inc"
%include "mrfm.inc"
%include "mrsyn.inc"
%include "mrout.inc"
%include "mrlist.inc"
%include "mrui.inc"
%include "mrcb.inc"
%include "mrtab.inc"
%include "os88pit.inc"
%include "os88spk.inc"

; =============================================================================
; data: the window, the menus, strings
; =============================================================================
mr_tpl:
    dw 8, 24, 624, 300              ; x, y, w, h (wm_fit clamps; the preference
    dw mr_ttl, mr_paint, mr_onkey, mr_onclick   ; below reshapes per screen)
mr_ttl:     db 'MIDIRack', 0

    OS88_PREFER mr_prefer, 628, 330,  718, 330,  638, 300

    OS88_MENUSET mr_menus, mr_ttl, mr_oncmd
        OS88_MENU mr_m_file, mr_i_file, 5
        OS88_MENU mr_m_play, mr_i_play, 6
        OS88_MENU mr_m_opt, mr_i_opt, 5
    OS88_MENUSET_END mr_menus
mr_m_file:  db 'File', 0
mr_i_file:  dw mr_it_add, mr_it_dir, mr_it_rem, mr_it_clr, mr_it_quit
MR_CMD_ADD  equ 0
MR_CMD_DIR  equ 1
MR_CMD_REM  equ 2
MR_CMD_CLR  equ 3
MR_CMD_QUIT equ 4
mr_it_add:  db 'Add...', 0
mr_it_dir:  db 'Load Directory...', 0
mr_it_rem:  db 'Remove', 0
mr_it_clr:  db 'Clear Playlist', 0
mr_it_quit: db 'Quit', 0
mr_m_play:  db 'Play', 0
mr_i_play:  dw mr_it_play, mr_it_pause, mr_it_stop, mr_it_prev, mr_it_next, \
               mr_it_loop
mr_it_play: db 'Play', 0
mr_it_pause: db 'Pause', 0
mr_it_stop: db 'Stop', 0
mr_it_prev: db 'Previous', 0
mr_it_next: db 'Next', 0
mr_it_loop: db 'Loop', 0
mr_m_opt:   db 'Options', 0
mr_i_opt:   dw mr_it_set, mr_it_info, mr_it_lev, mr_it_bg, mr_it_about
MR_CMD_SET  equ 0
MR_CMD_INFO equ 1
MR_CMD_LEV  equ 2
MR_CMD_BG   equ 3
MR_CMD_ABT  equ 4
mr_it_set:  db 'Settings...', 0
mr_it_info: db 'MIDI Info...', 0
mr_it_lev:  db 'Show Levels', 0
mr_it_bg:   db 'Play in Background', 0
mr_it_about: db 'About MIDIRack', 0

mr_s_ready:     db 'Ready', 0
mr_s_playing:   db 'Playing...', 0
mr_s_paused:    db 'Paused', 0
mr_s_stopped:   db 'Stopped', 0
mr_s_loading:   db 'Loading...', 0
mr_s_endlist:   db 'End of playlist', 0
mr_s_empty:     db 'The playlist is empty - Add a .MID file', 0
mr_s_notmidi:   db 'Not a Standard MIDI File', 0
mr_s_fmt2:      db 'MIDI format 2 is not played', 0
mr_s_smpte:     db 'SMPTE-timed files are not played', 0
mr_s_notrk:     db 'The file has no tracks', 0
mr_s_big:       db 'Too large: MIDIRack takes files up to 63 KB', 0
mr_s_nomem:     db 'Out of memory', 0
mr_s_rderr:     db 'The file could not be read', 0
mr_s_notask:    db 'No free task - close a program and retry', 0
mr_s_nofm:      db 'No FM chip (load SOUND.DRV in the Control Panel)', 0
mr_s_fmbusy:    db 'The FM chip is in use by another program', 0
mr_s_nosb:      db 'No Sound Blaster DSP for the synth', 0
mr_s_sberr:     db 'The Sound Blaster refused the stream', 0
mr_s_spkbusy:   db 'The PC speaker is busy', 0
mr_s_spkpaused: db 'Paused - Space plays on the speaker', 0
mr_s_spkplay:   db 'PC speaker - click or Space to pause', 0
mr_s_spkslow:   db 'The speaker cannot play at this rate here', 0
mr_s_full:      db 'The playlist is full', 0
mr_s_added:     db 'Added to the playlist', 0
mr_s_nomid:     db 'Not a .MID file', 0
mr_s_nodir:     db 'No .MID files in that folder', 0

%define OS88UI_BIMG
%define OS88UI_BOWN                 ; the colour face draws its own (13.8.10)
%define OS88UI_CHK
%define OS88UI_RAD
%define OS88UI_SCROLL
%define OS88UI_ABOUT
%include "os88ui.inc"
%if OS88UI_CK_SIZE != 12 || OS88UI_RD_SIZE != 18
  %error "mrui.inc sizes its check box and radio records by hand: os88ui.inc moved"
%endif
    OS88_BSS MR_BSS
    align 16, db 0
    OS88_IMAGE_END
