/* ============================================================================
 * os8088 - apps/lemmings/lemtext.c   (#included by lemmings.c)
 *
 * THE STRING ACCESSOR, AND NOT THE STRINGS (SPEC.md 92.3, 92.6).
 *
 * Every literal this program shows - the preview's seven format strings, the
 * postview's header and its nine result texts, the congratulation, the
 * 40-character status template, the cursor-lemming words, the rating and style
 * names, and every sentence that greys a control - lives in LEMSTR.LEM, a
 * 512-padded resource band written by tools/os88lem.py from a source table that
 * carries the defining reference for each row. That is about 2,000 bytes out of
 * the package IMAGE and into the DATA, and it is one of the two things that
 * make SPEC.md 92.6's resident budget close; the other is the wave-1 overlay
 * split.
 *
 * THE BAND IS READ ONCE INTO BSS AND INDEXED. bss is the cheap half - it costs
 * no file bytes and the loader zeroes it (LESSONS.md 5) - and a string that
 * cost a disk read every time it was drawn would be ~400 ms a sentence on the
 * target machine (PERFORMANCE.md). So lem_str_load() reads the whole band once
 * at launch and lem_str(id) is a pointer into it, which costs nothing per call.
 *
 * THE TWO HALVES CANNOT DRIFT. build/lemstr.h is GENERATED by the same tool
 * from the same table, so LEMS_<NAME> is a compile-time constant that moves
 * when the table moves; and lem_str_load() refuses a band whose count is short
 * of LEMS_COUNT rather than indexing off the end of a directory.
 *
 * ATTRIBUTION. The strings this file returns are the original's own on-screen
 * wording (Lemmings, (C) 1991 DMA Design / Psygnosis) and this port's own text;
 * every row's source is cited in tools/os88lem.py and repeated in the generated
 * build/lemstr.h. Nothing derived is in this file.
 * ==========================================================================*/

static unsigned char lem_strbuf[LEM_STRBUF];
static int  lem_strn;               /* rows the band actually carries */
static int  lem_strbytes;           /* what was read */

/* lem_u16 / lem_u8 - one little-endian word or byte out of a byte buffer. They
 * are functions and not casts because a cast would assume the buffer is
 * word-aligned, which a byte array read off a disk is not obliged to be, and an
 * unaligned word read is a silent two-byte penalty on an 8088 rather than a
 * fault. lem_u32dec() below is how this dialect reads a DWORD at all: there is
 * no `long` here (SPEC.md 73.7), so a 32-bit count never becomes a number - it
 * becomes its decimal text, which is the only form anything here prints. */
static int lem_u16(const unsigned char *p, int off)
{
    return (int)((unsigned)p[off] | ((unsigned)p[off + 1] << 8));
}

static int lem_u8(const unsigned char *p, int off)
{
    return (int)p[off];
}

/* lem_u32dec - the EXACT decimal of a little-endian dword, into `dst`.
 *
 * It is here because two of the three greying templates ask for a byte count in
 * BYTES - "the dirt graphic set is 96804 bytes = 95 clusters" - and the number
 * is a 32-bit field in LEMMAN.LEM's cost table while this dialect has no `long`
 * at all (SPEC.md 73.7, docs/C-TOOLCHAIN.md). Rounding it to kilobytes would
 * put a number on the glass that is not the number the converter refused on,
 * which is exactly what SPEC.md 47 rule 5 forbids.
 *
 * The method is long division in base 256 over the four bytes, which needs no
 * type wider than an int: a remainder is under 10, so `rem * 256 + byte` is
 * under 2,560 and every intermediate fits. Ten digits at most; `dst` is written
 * even for zero. */
static void lem_u32dec(const unsigned char *p, int off, char *dst, unsigned cap)
{
    /* static, not automatic: SS != DS in this model, so every addressable
     * object is a static and tools/cc8086.py refuses the other kind
     * (SPEC.md 73.5, os88.h rule 1). Nothing here is re-entrant and nothing
     * needs to be - it is called from one place, with the result copied out
     * before the next call. */
    static unsigned char d[4];
    static char rev[12];
    int i, n, cur, rem, nz;

    for (i = 0; i < 4; i++)
        d[i] = p[off + i];
    n = 0;
    for (;;) {
        rem = 0;
        nz = 0;
        for (i = 3; i >= 0; i--) {
            cur = rem * 256 + (int)d[i];
            d[i] = (unsigned char)(cur / 10);
            rem = cur - (int)d[i] * 10;
            if (d[i])
                nz = 1;
        }
        if (n < 11)
            rev[n++] = (char)('0' + rem);
        if (!nz)
            break;
    }
    i = 0;
    while (n > 0 && (unsigned)i + 1 < cap)
        dst[i++] = rev[--n];
    dst[i] = 0;
}

/* lem_str - the text of one string id. Never 0: an id the band does not carry
 * answers the empty string, so a caller that draws it puts nothing on the glass
 * rather than following a null pointer into the package image. */
static const char *lem_str(int id)
{
    int off;

    if (id <= 0 || id >= lem_strn)
        return "";
    off = lem_u16(lem_strbuf, LEM_STR_DIR + 2 * id);
    if (off <= 0 || off >= lem_strbytes)
        return "";
    return (const char *)(lem_strbuf + off);
}

/* lem_str_load - read the band and check it against what this was compiled
 * against. 0 = it is not usable and the launcher says so. */
static int lem_str_load(void)
{
    unsigned n;

    lem_strn = 0;
    lem_strbytes = 0;
    n = os88_file_read(lem_f_str, lem_strbuf, LEM_STRBUF);
    if (n == 0)
        return 0;
    if (n >= (unsigned)LEM_STRBUF)
        return 0;                       /* A BAND THAT FILLED THE BUFFER MAY
                                         * HAVE BEEN TRUNCATED, and a truncated
                                         * directory indexes strings that are
                                         * not there. It is 4,096 bytes today
                                         * against a 5,120 buffer
                                         * (docs/lemband-format.md), so this
                                         * refuses rather than half-working the
                                         * day somebody adds 4KB of greying
                                         * facts to tools/os88lem.py's table -
                                         * and 4,096 is the size the buffer
                                         * used to be, which this wave reached */
    lem_strbytes = (int)n;
    if (lem_strbuf[0] != 'L' || lem_strbuf[1] != 'S' ||
        lem_strbuf[2] != 'T' || lem_strbuf[3] != 'R')
        return 0;
    lem_strn = lem_u16(lem_strbuf, LEM_STR_COUNT);
    /* The band may carry MORE rows than this program knows about - a later
     * table only appends - but never fewer, because then LEMS_<NAME> would name
     * a row that is not there. */
    if (lem_strn < LEMS_COUNT) {
        lem_strn = 0;
        return 0;
    }
    return 1;
}

/* --- formatting -------------------------------------------------------------
 * There is no printf here and there is not going to be one: SmallerC's would
 * pull in a library this package cannot afford, and the only conversions this
 * program needs are an unsigned decimal and a %s substitution. The original's
 * format strings carry exactly those (Lemmix Base.Strings.pas:411-418), and
 * their SPACING is load-bearing - "You needed  %s" has two spaces, and on the
 * 640x350 surface that is where the value lands. So a substitution copies the
 * format byte for byte and only %s is special.
 *
 * A '%' NOT FOLLOWED BY 's' IS COPIED THROUGH, and that is not defensive
 * programming: Lemmix SPostviewScreen_Result3 is "Now try again for that few %
 * extra." and the sequence in it is "% e". tools/os88lem.py asserts that no
 * string in the band carries a '%' followed by anything but 's' or a space, so
 * the two halves agree about what a marker is. */

#define LEM_FMT_ARGS 8              /* the widest template is LEMS_MISS_STYLE's
                                     * seven markers (tools/os88lem.py) */

static const char *lem_arg[LEM_FMT_ARGS];
static int         lem_argn;

static void lem_arg_reset(void)
{
    lem_argn = 0;
}

static void lem_arg_add(const char *s)
{
    if (lem_argn < LEM_FMT_ARGS)
        lem_arg[lem_argn++] = s;
}

/* lem_arg_num - stage an unsigned decimal. Each number needs its OWN buffer,
 * because every argument is still live when the format runs: one shared
 * os88_utoa() scratch would give every marker the last number staged, which is
 * the shared-scratch defect LESSONS.md 13 names one level down.
 *
 * Flat and shifted, not two-dimensional: `buf[n][8]` is one more thing for the
 * compiler to lower and `buf + (n << 3)` is a shift the gate never has to find
 * a scratch register for (LESSONS.md 3's imul refusals). */
#define LEM_NUMW     16             /* ten digits and a NUL, rounded to a
                                     * SHIFT: lem_u32dec writes up to ten */
#define LEM_NUMSHIFT  4
static char lem_numbuf[LEM_FMT_ARGS * LEM_NUMW];

static char *lem_arg_slot(void)
{
    char *p;

    if (lem_argn >= LEM_FMT_ARGS)
        return 0;
    p = lem_numbuf + (lem_argn << LEM_NUMSHIFT);
    lem_arg[lem_argn] = p;
    lem_argn++;
    return p;
}

static void lem_arg_num(unsigned v)
{
    char *p = lem_arg_slot();

    if (p != 0)
        os88_utoa(v, p);
}

/* lem_arg_pct - stage "NN%", the share of `den` that `num` is.
 *
 * THE ORIGINAL'S THIRD PREVIEW LINE IS A PERCENTAGE AND NOT A COUNT. Lemmix
 * GameScreen.Preview.pas:275-278 computes
 * Percentage(LemmingsCount, RescueCount) and appends '%'; the raw count is the
 * other arm of an option, and LemmingsPercentages is IN TMiscOptions.DEFAULT
 * (Base.Types.pas:259), so the percentage is what the screen says. lemmings_3ds
 * import_level.c derives the same number - record[5]*100 / max_lemmings - and
 * prints "You need %3u%% of %2u". Fun 1 reads "10% To Be Saved", not "1".
 *
 * Percentage() is Trunc((N/Max) * 100) and this is that in integers: a rescue
 * count is at most the lemming count and a lemming count at most 100, so
 * num * 100 is at most 10,000 and fits a word - no `long`, which this dialect
 * does not have (SPEC.md 73.5). The '%' goes in the VALUE and never in the band
 * string, so tools/os88lem.py's "%s is the only marker" assertion stands.
 *
 * The same number is what waves 3 and 4's postview 'You rescued %s' and
 * 'You needed  %s' want, which is why it is one helper from the start. */
static void lem_arg_pct(unsigned num, unsigned den)
{
    char *p = lem_arg_slot();
    unsigned i;

    if (p == 0)
        return;
    if (den == 0 || num > 655u)         /* both counts come off a disk and
                                         * every byte read off one is hostile
                                         * (CLAUDE.md): 656 * 100 laps a word */
        num = 0;
    else
        num = (num * 100u) / den;
    os88_utoa(num, p);
    i = 0;
    while (p[i] != 0 && i + 2 < LEM_NUMW)
        i++;
    p[i] = '%';
    p[i + 1] = 0;
}

/* lem_arg_u32 - stage the exact decimal of a dword out of a byte buffer. It is
 * what puts "96804 bytes" rather than "95 KB" in a greying fact. */
static void lem_arg_u32(const unsigned char *buf, int off)
{
    char *p = lem_arg_slot();

    if (p != 0)
        lem_u32dec(buf, off, p, LEM_NUMW);
}

/* lem_fmt - substitute the staged arguments into `fmt`. A %s with no argument
 * left copies nothing. Always NUL-terminated; never writes past `cap`. */
static void lem_fmt(char *dst, unsigned cap, const char *fmt)
{
    unsigned o = 0;
    const char *arg;
    int used = 0;

    if (cap == 0)
        return;
    while (*fmt != 0 && o + 1 < cap) {
        if (fmt[0] == '%' && fmt[1] == 's') {
            arg = (used < lem_argn) ? lem_arg[used] : 0;
            used++;
            fmt += 2;
            if (arg != 0) {
                while (*arg != 0 && o + 1 < cap)
                    dst[o++] = *arg++;
            }
            continue;
        }
        dst[o++] = *fmt++;
    }
    dst[o] = 0;
}

/* lem_setn - an unsigned decimal into a caller's buffer. */
static void lem_setn(char *dst, unsigned cap, unsigned v)
{
    os88_utoa(v, lem_num);
    os88_strcpy(dst, lem_num, cap);
}

/* lem_fit - copy at most `cols` characters, so a 32-character level name in a
 * 22-cell pane is truncated HERE rather than drawn past the pane's edge:
 * os88_font_run() clips to the WINDOW and to nothing inside it, so a caller
 * that hands it a long string gets it painted over whatever is beside it. */
static void lem_fit(char *dst, unsigned cap, const char *src, int cols)
{
    unsigned o = 0;

    if (cols < 0)
        cols = 0;
    if ((unsigned)cols + 1 > cap)
        cols = (int)cap - 1;
    while (o < (unsigned)cols && src[o] != 0) {
        dst[o] = src[o];
        o++;
    }
    dst[o] = 0;
}

/* lem_trim - the leading spaces off a level name, at DISPLAY time and never in
 * the band. The original centres its titles by padding them - " Only floaters
 * can survive this" - and Lemmix calls Title.Trim before drawing it (the
 * converter keeps the bytes and strips only the TRAILING run, so nothing is
 * lost and the raw record still matches the disk). */
static const char *lem_trim(const char *s)
{
    while (*s == ' ')
        s++;
    return s;
}

/* --- the paragraph, and its wrap --------------------------------------------
 * Two of this launcher's three screens are a PARAGRAPH: the level's preview
 * fields (seven lines the original writes as seven format strings) and the
 * sentence behind a greyed control, which is 200-260 characters of the
 * converter's own prose and cannot fit a preview pane. Both are built into one
 * buffer by an ovl_* - neither is on a keystroke's path - and wrapped HERE,
 * because the wrap depends on the LIVE window width and the row composer asks
 * for line i on every repaint.
 *
 * '\r' IS A HARD BREAK. The nine postview result texts carry one each (Lemmix
 * Base.Strings.pas:423-460 - "ROCK BOTTOM! I hope for your sake\rthat you nuked
 * that level.") and the congratulation carries fifteen, so the character is
 * already the original's line separator and wave 5 needs no second convention.
 * '\n' is treated the same way, which is what the preview builder uses. */
#define LEM_PARA_MAX   560
#define LEM_WRAP_MAX    22

static char lem_para[LEM_PARA_MAX];
static int  lem_paran;              /* bytes in it */
static int  lem_wrapoff[LEM_WRAP_MAX];
static int  lem_wraplen[LEM_WRAP_MAX];
static int  lem_wrapn;
static char lem_wrapbuf[LEM_SH_COLS + 1];

static void lem_para_reset(void)
{
    lem_paran = 0;
    lem_para[0] = 0;
    lem_wrapn = 0;
}

/* lem_para_add - append, and a NUL is kept at the end so the buffer is always a
 * C string whatever the caller does next. Silently truncates: this is a display
 * buffer and a sentence that will not fit is a shorter sentence, not a fault. */
static void lem_para_add(const char *s)
{
    while (*s != 0 && lem_paran < LEM_PARA_MAX - 1)
        lem_para[lem_paran++] = *s++;
    lem_para[lem_paran] = 0;
}

static void lem_para_nl(void)
{
    if (lem_paran < LEM_PARA_MAX - 1)
        lem_para[lem_paran++] = '\n';
    lem_para[lem_paran] = 0;
}

/* lem_para_fmt - the same substitution, APPENDING to the paragraph buffer.
 * A greying fact is 200-260 characters (tools/os88lem.py's table) and lem_line
 * is one screen row wide, so the templates cannot be formatted into a row
 * buffer and then copied: they are formatted straight into the paragraph the
 * wrap reads. Declared beside lem_fmt because the two are one substitution with
 * two destinations, and neither may drift from the other's idea of a marker. */
static void lem_para_fmt(const char *fmt)
{
    const char *arg;
    int used = 0;

    while (*fmt != 0 && lem_paran < LEM_PARA_MAX - 1) {
        if (fmt[0] == '%' && fmt[1] == 's') {
            arg = (used < lem_argn) ? lem_arg[used] : 0;
            used++;
            fmt += 2;
            if (arg != 0) {
                while (*arg != 0 && lem_paran < LEM_PARA_MAX - 1)
                    lem_para[lem_paran++] = *arg++;
            }
            continue;
        }
        lem_para[lem_paran++] = *fmt++;
    }
    lem_para[lem_paran] = 0;
}

/* lem_wrap - greedy word wrap to the live content width. Words longer than the
 * width are broken rather than dropped, because a file name in a greying fact
 * ("LEMSP2_0.LEM is not on a 720KB disk...") is exactly the kind of word that is
 * longer than a narrow pane and is the whole point of the sentence. */
static void lem_wrap(void)
{
    int i, start, last, w, width;

    lem_wrapn = 0;
    width = lem_cols - 2;
    if (width < 8)
        width = 8;
    i = 0;
    while (i < lem_paran && lem_wrapn < LEM_WRAP_MAX) {
        if (lem_para[i] == '\n' || lem_para[i] == '\r') {
            lem_wrapoff[lem_wrapn] = i;
            lem_wraplen[lem_wrapn] = 0;
            lem_wrapn++;
            i++;
            continue;
        }
        start = i;
        last = -1;
        w = 0;
        while (i < lem_paran && w < width &&
               lem_para[i] != '\n' && lem_para[i] != '\r') {
            if (lem_para[i] == ' ')
                last = i;
            i++;
            w++;
        }
        if (i < lem_paran && lem_para[i] != '\n' && lem_para[i] != '\r' &&
            last > start)
            i = last;
        lem_wrapoff[lem_wrapn] = start;
        lem_wraplen[lem_wrapn] = i - start;
        lem_wrapn++;
        while (i < lem_paran && lem_para[i] == ' ')
            i++;
        if (i < lem_paran && (lem_para[i] == '\n' || lem_para[i] == '\r'))
            i++;
    }
}

static const char *lem_wrap_line(int i)
{
    int n;

    if (i < 0 || i >= lem_wrapn)
        return "";
    n = lem_wraplen[i];
    if (n > LEM_SH_COLS)
        n = LEM_SH_COLS;
    os88_memcpy(lem_wrapbuf, lem_para + lem_wrapoff[i], (unsigned)n);
    lem_wrapbuf[n] = 0;
    return lem_wrapbuf;
}
