"""Compile original title contours to desktop-native planes and outline bands.

Standard-library only. The reference is implemented as vector contours, not
an enlarged cartridge bitmap. Generated PNGs are pixel oracles for tests.
"""
import json
import struct
import zlib
import os88lz
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
W,H=432,144
EGA=[(0,0,0),(0,0,170),(0,170,0),(0,170,170),(170,0,0),(170,0,170),(170,85,0),(170,170,170),
     (85,85,85),(85,85,255),(85,255,85),(85,255,255),(255,85,85),(255,85,255),(255,255,85),(255,255,255)]

def polygon(points,x,y):
    inside=False
    a=points[-1]
    for b in points:
        if (a[1]>y)!=(b[1]>y) and x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]:inside=not inside
        a=b
    return inside

def mask(glyphs,height):
    return [any(sum(polygon(c,(x+.5-(48+i*86))/.9,(y+.5)*H/height/.9-32/.9) for c in contours)%2
                    for i,contours in enumerate(glyphs)) for y in range(height) for x in range(W)]

def inset(bits,height,radius):
    return [bits[y*W+x] and all(0<=x+dx<W and 0<=y+dy<height and bits[(y+dy)*W+x+dx]
                for dy in range(-radius,radius+1) for dx in range(-radius,radius+1)) for y in range(height) for x in range(W)]

def artwork(source,height,mono):
    face=mask(source['glyphs'],height)
    inner=inset(face,height,1 if mono else 3)
    if mono:return bytes(15 if a and not b else 0 for a,b in zip(face,inner))
    pixels=bytearray(W*height)
    for y in range(height):
        for x in range(W):
            if x+9<W and y>=8 and face[(y-8)*W+x+9]:pixels[y*W+x]=2
            if face[y*W+x]:pixels[y*W+x]=15
            if inner[y*W+x]:pixels[y*W+x]=10 if y<75 else 2
    # Narrow black inset separates the white bevel and green face.
    core=inset(face,height,5)
    for i,v in enumerate(inner):
        if v and not core[i]:pixels[i]=0
    return bytes(pixels)

def bitmap(pixels,width,height):
    return bytes(sum(bool(pixels[y*width+x+j])<<(7-j) for j in range(8))
                 for y in range(height) for x in range(0,width,8))

def packed(pixels):return bytes((pixels[i]<<4)|pixels[i+1] for i in range(0,len(pixels),2))
def planar(pixels,height):
    return bytes(sum(((pixels[y*W+x+j]>>plane)&1)<<(7-j) for j in range(8))
                 for plane in range(4) for y in range(height) for x in range(0,W,8))

def png(path,pixels,width,height):
    def chunk(tag,data):return struct.pack('>I',len(data))+tag+data+struct.pack('>I',zlib.crc32(tag+data)&0xffffffff)
    rgb=bytes(c for v in pixels for c in EGA[v])
    rows=b''.join(b'\0'+rgb[y*width*3:(y+1)*width*3] for y in range(height))
    path.write_bytes(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',width,height,8,2,0,0,0))+chunk(b'IDAT',zlib.compress(rows))+chunk(b'IEND',b''))

def build(out):
    source=json.loads((ROOT/'apps/1942/art/splash.json').read_text())
    fonts={s['name']:s for s in json.loads((ROOT/'apps/1942/art/sprites.json').read_text())}
    inc=['; Original desktop title art: generated by tools/1942front.py.',
         'N_FRONT_W equ 432','N_FRONT_H equ 144','N_FRONT_PLANE equ 324','N_FRONT_PACKED equ 1296']
    def emit(name,data):
        inc.append(name+':')
        for i in range(0,len(data),24):inc.append('    db '+','.join(map(str,data[i:i+24])))
    for tag,height,mono in [('vga',H,False),('herc',H,True),('cga',H//2,True)]:
        pixels=artwork(source,height,mono)
        bands=[]
        for row in range(0,height,6):
            band=pixels[row*W:(row+6)*W]
            raw=bitmap(band,W,6)+bytes(12) if mono else planar(band,6)+packed(band)
            assert len(raw)==(336 if mono else 2592)
            packed_band=os88lz.compress(raw)
            assert os88lz.decompress(packed_band,os88lz.LZ4,len(raw))==raw
            name='n_front_%s_%d'%(tag,row)
            emit(name,packed_band)
            bands.append('    dw %s,%d'%(name,len(packed_band)))
        inc.append('n_front_'+tag+':')
        inc.extend(bands)
        png(out/('1942-splash-'+tag+'.png'),pixels,W,height)
    for name,line in [('one','1 PLAYER'),('two','2 PLAYERS'),('resume','RESUME GAME'),('new','NEW GAME')]:
        for scale in (1,2):
            width=192;height=scale*8;pixels=bytearray(width*height)
            for j,ch in enumerate(line):
                font=bytes.fromhex(fonts['font%d'%ord(ch)]['pixels'])
                for y in range(height):
                    for x in range(8*scale):pixels[y*width+j*8*scale+x]=font[(y//scale)*8+x//scale]
            emit('n_front_%s%d'%(name,scale),bitmap(pixels,width,height))
    for scale in (1,2):
        height=12*scale
        pixels=bytes(polygon(source['plane'],x+.5,(y+.5)*2/scale) for y in range(height) for x in range(24))
        emit('n_front_plane%d'%scale,bitmap(pixels,24,height))
    (out/'1942front.inc').write_text('\n'.join(inc)+'\n')

if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument('-o',type=Path,default=Path('build'))
    args=parser.parse_args();args.o.mkdir(parents=True,exist_ok=True);build(args.o)
