#!/usr/bin/env python3
"""The build number the About box shows (SPEC.md 14.2), as a NASM include.

Writes `%define BUILD_NUM` / `%define BUILD_STR` into build/buildnum.inc, the
way tools/os88mini.py writes associco.inc and tools/os88font.py writes
font8x8.inc: a GENERATED include that the kernel names unconditionally and
`-I $(BUILD)/` finds. It is not tracked and never committed.

WHY A COMMIT COUNT, AND NOT A TIMESTAMP.  The number has to answer "which
build is this?" without breaking the one property this toolchain is built
around: the same source produces the same bytes.  tools/os88disk.py pins the
volume serial and every FAT timestamp for exactly that reason, and CLAUDE.md's
cheap resolution for "could this change a shipped byte" is to build twice and
md5sum the images.  A clock in the kernel image ends all of that - every build
differs from every other, and the comparison stops being able to say anything.
`git rev-list --count HEAD` is fixed for a given commit, so two people
building the same commit get the same images down to the byte, and the number
still goes up by one every time anybody commits.  It is also what the user
asked for over a hash: 334 is readable, ordered, and says how far along this
is; 764767b is none of those.

WHY IT REFUSES ON A SHALLOW CLONE.  `git rev-list --count` does not fail on a
shallow clone - it confidently counts the commits that are *there*.  This
checkout measured 281 before `git fetch --unshallow` and 333 after, and a web
session clones shallow by default, so the number would silently disagree
between two machines building the identical commit.  That is the exact failure
class CLAUDE.md's shallow-clone rule is about, and the answer is the same one:
check `--is-shallow-repository` first and do not answer at all rather than
answer wrongly.  BUILD_NUM 0 means "not known here", the About box then shows
the version line it always showed, and the note on stderr says how to fix it.
A missing build number is a cosmetic gap; a wrong one is a lie about which
bytes somebody is running, which on a project that mails floppy images to one
5150 in another country is the more expensive of the two.

Stdout is the number and nothing else, because the Makefile assigns it to a
variable at parse time.  Everything a human needs to read goes to stderr.
"""
import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _git(*args):
    """Run git in the repo root; None if it fails or is not there at all."""
    try:
        r = subprocess.run(("git",) + args, cwd=ROOT,
                           capture_output=True, text=True)
    except (OSError, ValueError):
        return None
    if r.returncode:
        return None
    return r.stdout.strip()


def build_number():
    """The commit count, or (0, why) when it cannot be trusted."""
    if _git("rev-parse", "--git-dir") is None:
        return 0, ("no git checkout here (a tarball, or git is not "
                   "installed)")

    # --is-shallow-repository is git 2.15+; the file is the older tell and
    # answers the same question, so a git too old for the flag still refuses
    # rather than reporting a truncated count.
    shallow = _git("rev-parse", "--is-shallow-repository")
    if shallow is None:
        gitdir = _git("rev-parse", "--absolute-git-dir") or os.path.join(ROOT,
                                                                        ".git")
        shallow = "true" if os.path.exists(os.path.join(gitdir,
                                                        "shallow")) else "false"
    if shallow != "false":
        return 0, ("this is a SHALLOW clone, so the commit count here is not "
                   "the commit count - run `git fetch --unshallow`")

    count = _git("rev-list", "--count", "HEAD")
    if not count or not count.isdigit():
        return 0, "git could not count HEAD (an empty history?)"
    return int(count), None


def render(num):
    """The include's text. BUILD_NUM 0 is the 'not known here' value."""
    return "".join((
        "; GENERATED by tools/buildnum.py - not tracked, not edited by hand.\n",
        ";\n",
        "; The build number (SPEC.md 14.2): commits in this checkout's\n",
        "; history, so it goes up by one per commit and is the same number\n",
        "; on every machine that builds this commit. 0 means the build could\n",
        "; not determine it and the About box shows no build line at all -\n",
        "; a missing number rather than a wrong one.\n",
        "%%define BUILD_NUM %d\n" % num,
        "%%define BUILD_STR '%d'\n" % num,
    ))


def write_if_changed(path, text):
    """Leave the mtime alone when the number has not moved.

    The kernel depends on this file, so rewriting it unconditionally would
    reassemble the kernel, both boot sectors and every image on every single
    `make` - and the point of a parse-time generator is that it costs nothing
    when nothing changed.
    """
    try:
        with open(path) as f:
            if f.read() == text:
                return False
    except OSError:
        pass
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    return True


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-o", "--out", help="the .inc to write (build/buildnum.inc)")
    a = ap.parse_args(argv)

    num, why = build_number()
    if why:
        sys.stderr.write("buildnum: no build number - %s\n" % why)
    if a.out:
        write_if_changed(a.out, render(num))
    print(num)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
