#!/usr/bin/env python3
"""Rebuild the native Gorillas art and ink tables (SPEC.md 98.1).

Reference: reference/gorillas/gorilla.bas, SetScreen/DrawGorilla/DoSun.
The BASIC's EGA palette values are six-bit rgbrgb colors, not VGA indices.
No imaging libraries or runtime external assets are needed.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Game ink -> EGA palette value. The original's 0,1,2,3,5,6,7 are literal
# SetScreen values. 8/14/15 are its default dark gray/yellow/white colors.
EGA = (1, 46, 44, 54, 0, 7, 4, 3, 56, 63, 38, 20, 56, 0, 62, 63)
DESKTOP = (1, 6, 12, 14, 0, 7, 4, 3, 8, 15, 14, 6, 8, 0, 14, 15)
APE = (
    '0000011111100000',
    '000011AAAA110000',
    '0001111111110000',
    '0001100000110000',
    '0001110101110000',
    '0000111111100000',
    '0000011111000000',
    '0011111111111100',
    '0111A111111A1110',
    '1111A110011A1111',
    '1111A100001A1111',
    '111B11111111B111',
    '111B11111111B111',
    '111B11111111B111',
    '011B11111111B110',
    '0000111BB1110000',
    '0001111001111000',
    '00111B0000B11100',
    '01111B0000B11110',
    '0111110000111110',
)


def ega_rgb6(value):
    return tuple(42 * ((value >> bit) & 1) + 21 * ((value >> (bit + 3)) & 1)
                 for bit in (2, 1, 0))


def generate():
    result = ['; Generated by tools/gorillas_art.py; see reference/README.md.',
              '; Semantic ink -> desktop packed pixels. Orange blends red/yellow.',
              'gr_winmap:']
    mapped = [(DESKTOP[i >> 4] << 4) | DESKTOP[i & 15] for i in range(256)]
    def emit(values, kind='db', per=16):
        for i in range(0, len(values), per):
            result.append('    ' + kind + ' ' + ','.join(str(v) for v in values[i:i+per]))
    emit(mapped)
    result.append('gr_winx2:')
    pairs = [0xCE if i == 1 else 17 * DESKTOP[i] for i in range(16)]
    emit([pairs[i >> 4] | (pairs[i & 15] << 8) for i in range(256)], 'dw', 8)
    result.append('; Each packed byte contributes two bits to a VGA plane.\ngr_planebits:')
    for plane in range(4):
        emit([(((i >> (plane + 4)) & 1) << 1) | ((i >> plane) & 1)
              for i in range(256)])
    result.append('; Exact QBasic EGA colors in the VGA DAC\ngr_dac:')
    emit([c for value in EGA for c in ega_rgb6(value)], per=12)
    result.append('; 16x20 packed 4bpp gorilla. 0=transparent, 1/A/B=body/light/shadow.\ngr_ape:')
    assert len(APE) == 20 and all(len(row) == 16 for row in APE)
    emit([int(row[i:i+2], 16) for row in APE for i in range(0, 16, 2)], per=8)
    # Lift one arm while retaining the original face/chest and opposite arm.
    left = [list(row) for row in APE]
    for y in range(7, 15):
        for x in range(3):
            left[y][x] = '0'
    for y in range(2, 10):
        for x in range(3):
            left[y][x] = 'A' if x == 1 else '1'
    left[8][3] = left[9][3] = '1'
    for name, rows in (('left', left), ('right', [row[::-1] for row in left])):
        result.append('gr_ape' + name + ':')
        emit([int(''.join(row[i:i+2]), 16) for row in rows
              for i in range(0, 16, 2)], per=8)
    # Opaque native intro sprites: no pixel plotting or palette conversion
    # during animation. Each mode contains left then right raised-arm poses.
    cga = (0, 3, 2, 3, 0, 2, 2, 1, 0, 3, 3, 2, 2, 0, 3, 3)
    for mode, scale in (('mono', 1), ('mono', 2), ('win', 1),
                        ('win', 2), ('cga', 1), ('vga', 2),
                        ('planar', 1), ('planar', 2)):
        result.append('gr_front_' + mode + str(scale) + ':')
        for rows in (left, [row[::-1] for row in left]):
            pixels = [[int(p, 16) for p in row] for row in rows]
            if mode in ('vga', 'planar'):
                if mode == 'planar':
                    pixels = [[v for p in row for v in
                               ((12, 14) if scale == 2 and p == 1 else
                                (DESKTOP[p],)*scale)] for row in pixels]
                for plane in range(4):
                    for row in pixels:
                        bits = ''.join(str((p >> plane) & 1)*
                                       (scale if mode == 'vga' else 1) for p in row)
                        emit([int(bits[i:i+8], 2) for i in range(0, len(bits), 8)])
            else:
                for row in pixels:
                    bits = ''
                    for p in row:
                        if mode == 'mono':
                            bits += str(int(p != 0))*scale
                        elif mode == 'cga':
                            bits += format(cga[p], '02b')
                        elif scale == 2 and p == 1:
                            bits += '11001110'  # desktop orange stipple
                        else:
                            bits += format(DESKTOP[p], '04b')*scale
                    emit([int(bits[i:i+8], 2) for i in range(0, len(bits), 8)])
    # Five marching-light masks: top/bottom (256x3), left/right (8x128).
    # Sides include corners so all four rectangles agree where they overlap.
    result.append('gr_front_lights:')
    phases = []
    for phase in range(5):
        lit = set()
        def spark(x, y):
            lit.update((x+dx, y+dy) for dx, dy in ((1, 0), (0, 1),
                                                (1, 1), (2, 1), (1, 2)))
        for x in range(phase*4, 253, 20):
            spark(x, 0)
            spark(252-x, 125)
        for y in range(phase*4+5, 123, 20):
            spark(0, y)
            spark(253, 125-y)
        phases.append(lit)
        for x, y, w, h in ((0, 0, 256, 3), (0, 125, 256, 3),
                            (0, 0, 8, 128), (248, 0, 8, 128)):
            for yy in range(y, y+h):
                bits = ''.join(str(int((xx, yy) in lit)) for xx in range(x, x+w))
                emit([int(bits[i:i+8], 2) for i in range(0, len(bits), 8)])
    result.append('gr_lightruns:')
    for phase in range(5):
        result.append('    dw gr_lightrun%d_0, gr_lightrun%d_1' % (phase, phase))
    for phase, lit in enumerate(phases):
        changed = lit | phases[(phase-1) % 5]
        for side, x in enumerate((0, 248)):
            result.append('gr_lightrun%d_%d:' % (phase, side))
            rows = [y for y in range(3, 125)
                    if any((xx, y) in changed for xx in range(x, x+8))]
            while rows:
                first = last = rows.pop(0)
                while rows and rows[0] <= last+2:
                    last = rows.pop(0)
                result.append('    dw %d' % (phase*448+192+side*128+first))
                emit([first, last-first+1])
            result.append('    dw 0\n    db 0,0')
    # Circle, rays and smile in the BASIC's proportions, in a small model grid.
    sun = [[0] * 25 for _ in range(21)]
    for ex, ey in ((12, 0), (0, 10), (9, 7), (6, 9), (11, 4)):
        for signx in (-1, 1):
            for signy in (-1, 1):
                steps = max(ex, ey)
                for n in range(steps + 1):
                    x = 12 + signx * round(ex * n / steps)
                    y = 10 + signy * round(ey * n / steps)
                    sun[y][x] = 1
    for y in range(21):
        for x in range(25):
            if (x-12)**2 + (y-10)**2 <= 49:
                sun[y][x] = 1
    for x, y in ((9,8),(15,8),(8,12),(9,13),(10,14),(11,14),
                 (12,14),(13,14),(14,14),(15,13),(16,12)):
        sun[y][x] = 0
    result.append('; 25x21 sun mask, ray tips and facial cutouts.\ngr_sunart:')
    for row in sun:
        emit(row, per=25)
    return '\n'.join(result) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'apps/gorillas/grart.inc'
    generated = generate()
    if args.check:
        if output.read_text() != generated:
            raise SystemExit('grart.inc is stale: run python3 tools/gorillas_art.py')
        print('gorillas_art: committed artwork and palette tables match')
    else:
        output.write_text(generated)
        print('gorillas_art: wrote', output)


if __name__ == '__main__':
    main()
