#!/usr/bin/env python3
"""Compile three original 16-bar Gorillas FM scores (scientific pitch names).

Each row is one eighth note: duration in BIOS ticks, then three Hz words.
All voices retrigger; '-' is a rest. No samples or runtime pitch conversion.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

# Eight-bar call and response phrases, followed by eight-bar answers.
# Chords are (bass root, fifth, three accompaniment tones).
CHORDS = {
    'C': 'C3 G3 E4 G4 C5', 'Am': 'A2 E3 C4 E4 A4',
    'F': 'F2 C3 A3 C4 F4', 'G': 'G2 D3 B3 D4 G4',
    'Dm': 'D3 A3 F4 A4 D5', 'Bb': 'Bb2 F3 D4 F4 Bb4',
    'A': 'A2 E3 C#4 E4 A4', 'Em': 'E3 B3 G4 B4 E5',
    'D': 'D3 A3 F#4 A4 D5',
}

TRACKS = [
    ('rumble', 'Rooftop Rumble', (3, 3),
     'C Am F G C Am F G C Em F G Am F G G'.split(), [
         'E5 - G5 A5 G5 E5 D5 -', 'C5 E5 A5 - G5 E5 C5 -',
         'A4 C5 F5 G5 A5 - G5 F5', 'D5 G5 B5 - A5 G5 D5 -',
         'E5 G5 C6 - B5 G5 E5 G5', 'A5 - E5 C5 E5 G5 A5 -',
         'F5 A5 G5 F5 E5 C5 D5 -', 'B4 D5 G5 A5 G5 - D5 -',
         'G5 E5 C5 E5 G5 A5 C6 -', 'B5 G5 E5 - G5 B5 A5 G5',
         'A5 F5 C5 F5 A5 C6 A5 -', 'B5 A5 G5 D5 G5 - A5 B5',
         'C6 A5 E5 G5 A5 - G5 E5', 'F5 A5 C6 A5 G5 F5 E5 C5',
         'D5 G5 B5 A5 G5 D5 B4 D5', 'G5 - D5 B4 D5 - B4 -',
     ]),
    ('moonlit', 'Moonlit Mischief', (4, 4),
     'Dm Bb F A Dm Bb G A Dm F Bb A G Dm Bb A'.split(), [
         'D5 - A5 - F5 E5 D5 -', 'F5 - D5 F5 Bb5 - A5 -',
         'A5 G5 F5 - C5 - F5 -', 'E5 - C#5 E5 A5 G5 E5 -',
         'F5 - A5 C6 A5 - F5 E5', 'D5 F5 Bb5 - A5 F5 D5 -',
         'B4 - D5 G5 A5 G5 D5 -', 'C#5 E5 A5 - G5 E5 C#5 -',
         'A5 - D6 A5 F5 - E5 D5', 'C6 - A5 G5 F5 A5 C6 -',
         'Bb5 A5 F5 - D5 F5 Bb5 -', 'A5 - G5 E5 C#5 E5 G5 -',
         'G5 B5 A5 G5 D5 - B4 D5', 'F5 A5 D6 - C6 A5 F5 E5',
         'D5 F5 Bb5 A5 F5 D5 F5 -', 'E5 C#5 A4 - C#5 E5 A5 -',
     ]),
    ('boulevard', 'Banana Boulevard', (4, 2),
     'G F C G G F C D G Am C D Em C F D'.split(), [
         'G5 B5 - D6 B5 G5 A5 B5', 'A5 C6 - A5 G5 F5 A5 -',
         'G5 E5 - G5 C6 B5 G5 E5', 'D5 G5 - B5 A5 G5 D5 -',
         'B5 D6 - B5 G5 A5 B5 G5', 'C6 A5 - G5 F5 A5 C6 -',
         'E5 G5 - C6 B5 G5 E5 C5', 'F#5 A5 - D6 C6 A5 F#5 -',
         'D6 B5 - G5 A5 B5 D6 -', 'C6 A5 - E5 G5 A5 C6 B5',
         'G5 C6 - E6 D6 C6 B5 G5', 'A5 F#5 - D5 F#5 A5 C6 -',
         'B5 G5 - E5 G5 B5 D6 B5', 'C6 G5 - E5 G5 C6 B5 G5',
         'A5 F5 - C5 F5 A5 C6 A5', 'F#5 A5 - C6 A5 F#5 D5 -',
     ]),
]


def hz(note):
    if note == '-':
        return 0
    m = re.fullmatch(r'([A-G])([#b]?)([0-8])', note)
    assert m, note
    pitch = dict(C=0, D=2, E=4, F=5, G=7, A=9, B=11)[m[1]]
    pitch += {'': 0, '#': 1, 'b': -1}[m[2]]
    midi = 12 * (int(m[3]) + 1) + pitch
    value = round(440 * 2 ** ((midi - 69) / 12))
    assert 19 <= value <= 6208
    return value


def rows(track):
    _, _, ticks, chords, melody = track
    assert len(chords) == len(melody) == 16
    for chord, bar in zip(chords, melody):
        lead = bar.split()
        assert len(lead) == 8
        root, fifth, third, upper, top = CHORDS[chord].split()
        bass = [root, '-', fifth, '-', root, '-', fifth, '-']
        arp = ['-', third, upper, top, '-', upper, third, upper]
        for i, notes in enumerate(zip(lead, bass, arp)):
            yield (ticks[i % 2], *(hz(n) for n in notes))


def generate():
    out = ['; Generated by tools/gorillas_bgm.py. Original Gorillas scores.',
           '; Byte ticks, then melody/bass/accompaniment Hz words. Zero ticks loops.',
           'gr_bgmtracks: dw gr_bgmrumble, gr_bgmmoonlit, gr_bgmboulevard']
    for track in TRACKS:
        out += [f'gr_bgm{track[0]}:', f'    ; {track[1]}: 16 bars, 4/4.']
        for ticks, lead, bass, arp in rows(track):
            out += [f'    db {ticks}', f'    dw {lead},{bass},{arp}']
        out += ['    db 0']
    return '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    path = ROOT / 'apps/gorillas/grbgmdata.inc'
    if args.check:
        assert path.read_text() == generate(), 'grbgmdata.inc is stale'
        print('gorillas_bgm: three original scores match')
    else:
        path.write_text(generate())


if __name__ == '__main__':
    main()
