#!/usr/bin/env python3
"""Compile the reference PLAY strings into nonblocking speaker note tables.

QBasic octave 0 starts at C=65.406 Hz (PLAY's octave numbering differs from
scientific pitch notation). Durations round to the OS's 18.2 Hz tone ticks;
32nd/64th notes have a one-tick minimum. No runtime BASIC parser is needed.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def compile_mml(text, tempo=160):
    octave, length = 4, 4
    result = []
    tokens = re.findall(r'M[BFNLS]|[TOLN]\d+|[A-G][+#-]?\d*', text.upper())
    for token in tokens:
        op = token[0]
        if op == 'M':
            continue
        if op == 'T':
            tempo = int(token[1:])
        elif op == 'O':
            octave = int(token[1:])
        elif op == 'L':
            length = int(token[1:])
        else:
            if op == 'N':
                assert token == 'N0'
                freq, duration = 0, length
            else:
                note = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}[op]
                tail = token[1:]
                if tail[:1] in ('+', '#', '-'):
                    note += -1 if tail[0] == '-' else 1
                    tail = tail[1:]
                duration = int(tail) if tail else length
                freq = round(440 * 2 ** ((note + (octave - 2)*12 - 9)/12))
            ticks = max(1, round(240 / tempo / duration * 18.2065))
            result.append((freq, ticks))
    return result


def generate():
    source = (ROOT / 'reference/gorillas/gorilla.bas').read_text()
    def plays(sub):
        body = source.split('\nSUB ' + sub + '\n', 1)[1].split('END SUB', 1)[0]
        return re.findall(r'PLAY "([^"]+)"', body)
    dance = plays('GorillaIntro (Player1$, Player2$)')
    songs = {
        'intro': plays('Intro')[0],
        'dance': ''.join(dance[:4]) + ''.join(dance[4:])*4,
        'throw': re.search(r'PLAY "(MBo0[^\"]+)"', source)[1],
        'impact': plays('DoExplosion (x#, y#)')[0],
        'hit': 'MBO0L16EFGEFDC',
    }
    out = ['; Generated by tools/gorillas_music.py from reference/gorillas/gorilla.bas.',
           '; (Hz, BIOS ticks) pairs; FFFF terminates a sequence.']
    for name, mml in songs.items():
        out += ['gr_music' + name + ':', '    ; PLAY "' + mml + '"']
        out += ['    dw %d,%d' % note for note in compile_mml(mml)]
        out += ['    dw 0ffffh']
    return '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    path = ROOT / 'apps/gorillas/grmusic.inc'
    generated = generate()
    if args.check:
        assert path.read_text() == generated, 'grmusic.inc is stale'
        print('gorillas_music: reference PLAY scores match')
    else:
        path.write_text(generated)


if __name__ == '__main__':
    main()
