#!/usr/bin/env python3
"""os88mini - reduce a package's embedded 16x16 icon to the 8x8 glyph the
association table caches (SPEC.md 54, docs/ASSOC-PLAN.md 2.1/2.5).

Emits one NASM line per package, for %include into kernel/assoc.inc, so the
kernel ships knowing what its own default applications look like and needs no
disk read to draw a document icon for them. GENERATED, never hand-pasted:
pasted bytes go stale in silence when an app's icon changes, where the make
dependency cannot.

Usage:  os88mini.py -o build/associco.inc STEM=build/paint.o88 ...

The reduction is MAJORITY-OF-2x2 and must stay byte-identical to assoc_reduce
in kernel/assoc.inc: a 2x2 block of the source's DATA plane lights if two or
more of its four pixels are ink. OR-of-4 turns a typical 40%-ink Mac icon into
a near-solid blob and point-sampling drops every one-pixel stroke; majority is
the one that keeps a silhouette at 8x8 on a 1bpp adapter.

Only the data plane is reduced. The glyph is OR'd into a page interior the
frame has already cleared to white, so "ink" is the whole of what it means -
which is what makes the cached glyph 8 bytes and not 16.
"""
import argparse
import sys

HDR = 32                       # header bytes before the icon (SPEC.md 20.2)
ICON = 64                      # 16 mask words + 16 data words
MAGIC = 0x384F                 # 'O','8'


def fail(msg):
    sys.stderr.write(f"os88mini: {msg}\n")
    sys.exit(1)


def data_rows(path):
    """The 16 data words of a package's embedded icon, MSB = leftmost pixel."""
    try:
        with open(path, "rb") as f:
            img = f.read()
    except OSError as e:
        fail(f"cannot read {path}: {e}")
    if len(img) < HDR + ICON:
        fail(f"{path}: {len(img)} bytes, too short to hold a header + icon")
    if int.from_bytes(img[0:2], "little") != MAGIC:
        fail(f"{path}: bad magic, not a .o88")
    if not img[3] & 1:
        fail(f"{path}: flags bit 0 clear - this package ships no icon, so it "
             f"has no glyph to bake. Drop it from the default table.")
    # bytes 32..95: 16 mask words then 16 data words. The mask is the white
    # underlay and is deliberately not reduced (see the module docstring).
    base = HDR + 32
    return [int.from_bytes(img[base + 2 * y:base + 2 * y + 2], "little")
            for y in range(16)]


def reduce8(rows):
    """16x16 -> 8x8, majority of each 2x2 block. Returns 8 bytes, bit 7 left."""
    out = []
    for oy in range(8):
        b = 0
        for ox in range(8):
            lit = 0
            for dy in (0, 1):
                row = rows[2 * oy + dy]
                for dx in (0, 1):
                    if row >> (15 - (2 * ox + dx)) & 1:
                        lit += 1
            if lit >= 2:
                b |= 1 << (7 - ox)
        out.append(b)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("pairs", nargs="+", metavar="STEM=path.o88")
    args = ap.parse_args()

    lines = ["; GENERATED by tools/os88mini.py - do not edit.",
             "; The 8x8 glyphs of SPEC.md 54's default associations, reduced",
             "; from each package's own embedded icon at BUILD time so the",
             "; kernel needs no disk read to draw their document icons.",
             ""]
    for pair in args.pairs:
        if "=" not in pair:
            fail(f"expected STEM=path.o88, got {pair!r}")
        stem, path = pair.split("=", 1)
        stem = stem.upper()
        if not 1 <= len(stem) <= 8:
            fail(f"{stem!r}: an 8.3 stem is 1..8 characters")
        g = reduce8(data_rows(path))
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in g) +
                     f"    ; {stem}")
    lines.append("")

    try:
        with open(args.output, "w") as f:
            f.write("\n".join(lines))
    except OSError as e:
        fail(f"cannot write {args.output}: {e}")
    n = len(args.pairs)
    print(f"os88mini: {n} glyph(s) -> {args.output}")


if __name__ == "__main__":
    main()
