#!/usr/bin/env python3
"""Extract the Roklan Atari disk source's data into the native Pac-Man port.

Usage: python3 tools/pacman_assets.py ../atari-pacman [--check]
The generated include is committed; ordinary builds need neither this tool
nor the source checkout. Input is legacy CRLF assembly with CP/M EOF bytes.
"""
import argparse
from pathlib import Path
import re


def block(source, label):
    lines = source.splitlines()
    start = next(i for i, l in enumerate(lines)
                 if re.match(r'^' + re.escape(label) + r'(?:\s|$)', l))
    data = []
    for i, line in enumerate(lines[start:]):
        if i and line and not line[0].isspace() and not line.startswith(';'):
            break
        match = re.search(r'(?:\bDB\b|\.byte)\s+(.+)', line, re.I)
        if match:
            for token in match[1].split(';')[0].split(','):
                token = token.strip()
                if not re.fullmatch(r'\$[0-9A-Fa-f]+|\d+', token):
                    raise ValueError(f'{label}: not a literal: {token}')
                data.append(int(token[1:], 16) if token.startswith('$') else int(token))
    return data


def generate(root):
    dat1 = (root / 'PACDAT1.ASM').read_bytes().decode('latin1')
    dat2 = (root / 'PACDAT2.ASM').read_bytes().decode('latin1')
    chars = block(dat1, 'PACCHR')
    maze = block(dat1, 'DATMAZ')
    assert len(maze) == 920 and maze.count(1) == 256 and maze.count(2) == 4
    out = ['; Generated by tools/pacman_assets.py from Roklan PACDAT1/2.ASM.',
           '; Source attribution and adaptations: apps/pacman/README.md.',
           '; Packed tiles: Atari 2-bit pixels become doubled 4bpp pixels.',
           '; 0 black, 1 light-blue walls, 2 light-red, 3 white dots.']

    def emit(name, values):
        out.append('pm_' + name + ':')
        for i in range(0, len(values), 16):
            out.append('    db ' + ','.join(f'0x{x:02X}' for x in values[i:i + 16]))

    emit('maze_source', maze[:880])
    used = sorted(set(maze[:880]))
    offsets = {code: index * 32 for index, code in enumerate(used)}
    out.append('pm_tile_offsets:')
    for i in range(0, max(used) + 1, 12):
        out.append('    dw ' + ','.join(str(offsets.get(code, 0))
                                       for code in range(i, min(i + 12, max(used) + 1))))
    tiles = []
    compact = [row for code in used for row in chars[code * 8:code * 8 + 8]]
    for row in compact:
        for shift in (6, 4, 2, 0):
            color = (0, 9, 12, 15)[(row >> shift) & 3]
            tiles.append(color * 17)
    emit('tiles', tiles)
    for name in ('VTABLE', 'HTABLE', 'HOMEHV', 'BLUTIM', 'STARTV'):
        emit(name.lower(), block(dat2, name))
    emit('junctions', sum((block(dat2, f'HTAB{i:02}') for i in range(1, 11)), []))
    for name in ('PACDOT', 'PACRGT', 'PACLFT', 'PACTOP', 'PACBOT',
                 'MONSUP', 'MONSDN', 'MONSLF', 'MONSRT', 'MONSFL', 'MONSEY'):
        # PACTOP is followed by PACDIE: the open-up frame is that label.
        emit(name.lower(), block(dat2, name)[:10])
    out.append('pm_fruit_points: dw 100,300,500,500,700,700,1000,1000,2000,2000,3000,3000,5000')
    return '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('source', type=Path)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    target = Path(__file__).resolve().parents[1] / 'apps/pacman/assets.inc'
    result = generate(args.source)
    if args.check:
        if target.read_text() != result:
            raise SystemExit('Pac-Man assets differ from source; regenerate them')
        print('Pac-Man assets match the Atari source')
    else:
        target.write_text(result)


if __name__ == '__main__':
    main()
