#!/usr/bin/env python3
"""pxlink: the package's variables, by name, for a LINKED part (SPEC.md 106.20).

    python3 tools/pxlink.py build/pixel.bin -o build/pxlink.inc

PiXEL's SIMPLE part (apps/pixel/pxsimp.asm) is the five simple formats'
readers moved out of the resident package and still reading and writing the
package's own variables - [px_cur + PXR_SW], [px_spal], [px_rpos] - through
DS, which SPEC.md 106.5's rule 2 allows. A separately assembled part has to
learn where those variables are, and this is how: pixel.asm is assembled
again with a NASM symbol map, the result must be BYTE-IDENTICAL to the
build/pixel.bin it is linked against (or the map describes another package
and the tool refuses), and every symbol at or past the image's end - the
package's bss, and nothing else - is written out as an equate.

ONLY THE BSS, ON PURPOSE. A code label written out would assemble a part's
`call px_emit` as a near call into the PART's own segment at the package's
offset, which is silent and wrong; leaving every symbol below the image's
end undefined makes that an assembly error instead. Tables the moved code
reads are copied into the part.

THE STAMP. The image and bss sizes from the package's header are written as
PXL_IMAGE and PXL_BSS; the part compares them with the header of the package
it is called from (DS:8 and DS:10) before it touches a variable, so a part
from another build answers PXD_LINK rather than writing the wrong bytes.
"""
import argparse
import os
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bin")
    ap.add_argument("-o", required=True)
    a = ap.parse_args()
    want = open(a.bin, "rb").read()
    image, bss = struct.unpack_from("<HH", want, 8)
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "p.asm")
        mp = os.path.join(d, "p.map")
        out = os.path.join(d, "p.bin")
        open(src, "w").write(
            open(os.path.join(ROOT, "apps", "pixel", "pixel.asm")).read()
            + "\n[map symbols %s]\n" % mp)
        subprocess.run(["nasm", "-f", "bin", "-w+error",
                        "-I", os.path.join(ROOT, "apps") + "/",
                        "-I", os.path.join(ROOT, "apps", "pixel") + "/",
                        "-o", out, src], check=True)
        if open(out, "rb").read() != want:
            sys.exit("pxlink: %s is not apps/pixel/pixel.asm as it stands - "
                     "rebuild it first" % a.bin)
        syms = []
        for line in open(mp):
            f = line.split()
            if len(f) == 3 and all(c in "0123456789ABCDEF" for c in f[0]):
                v = int(f[1], 16)
                if v >= image and not f[2].startswith("..") \
                        and "." not in f[2]:
                    syms.append((f[2], v))
    syms.sort(key=lambda s: (s[1], s[0]))
    lines = ["; GENERATED by tools/pxlink.py from %s - do not edit (SPEC.md "
             "106.20)" % os.path.basename(a.bin),
             "; the package's bss, by name, for a part linked against it",
             "PXL_IMAGE   equ %d" % image,
             "PXL_BSS     equ %d" % bss]
    lines += ["%-24s equ 0x%04X" % (n, v) for n, v in syms]
    text = "\n".join(lines) + "\n"
    open(a.o, "w").write(text)
    print("pxlink: %d package variables into %s" % (len(syms), a.o))
    return 0


if __name__ == "__main__":
    sys.exit(main())
