#!/usr/bin/env python3
"""apps/skies/csart.inc is GENERATED by tools/csart.py and checked in (SPEC.md
88.10): regenerate it into a temporary file and hold the two to each other,
so the include cannot drift from the drawing that produced it - the same
discipline docs/INDEX.md has with tools/os88index.py."""
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    fd, tmp = tempfile.mkstemp(prefix="csart_", suffix=".inc")
    os.close(fd)
    try:
        r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "csart.py"),
                            "-o", tmp], capture_output=True, text=True)
        if r.returncode:
            sys.exit("t_csart: tools/csart.py failed:\n" + r.stderr[:400])
        want = open(tmp).read()
    finally:
        os.unlink(tmp)
    have = open(os.path.join(ROOT, "apps", "skies", "csart.inc")).read()
    if want != have:
        sys.exit("t_csart: apps/skies/csart.inc is not what tools/csart.py "
                 "generates - run `python3 tools/csart.py` and commit the result")
    print("  csart: apps/skies/csart.inc matches tools/csart.py (%d lines)"
          % have.count("\n"))


if __name__ == "__main__":
    main()
