#!/usr/bin/env python3
"""MIDIRACK'S GENERATED TABLES AND SHIPPED SONGS (SPEC.md 105.6.1, 105.3.1).

    python3 tests/unit/t_midtab.py

apps/midirack/mrtab.inc - the F-Numbers, the synth's pitches, the two level
curves, the General MIDI names, the FM bank and kit and the synth's voicing -
is GENERATED by tools/os88midi.py. A hand edit, or a tool change nobody
regenerated, would put the player and its reference apart while both still
assembled; this fails first, naming the file.

THE SONGS ARE READ TWICE, BY TWO READERS THAT SHARE NO CODE: the composer's own
independent checker (tools/os88midsong.py --check) and os88midi.py's reference
sequencer, which is the one the player's gates compare the machine against.
Each song's length must agree to 1 ms between the two, and every song must be
one the player takes: format 0 or 1, ticks-a-quarter timing, at most 24
tracks and MR_FILEMAX (63 KB). A reader that drifted from the other - a
running-status or tempo-map bug - fails here, on the host, before a guest row
ever boots.

Broken on purpose (a byte changed in mrtab.inc, or a song truncated) it FAILS.
"""
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(
    __file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import os88midi as om       # noqa: E402

INC = os.path.join(ROOT, "apps", "midirack", "mrtab.inc")
SONGS = os.path.join(ROOT, "apps", "midirack", "songs")
MAXTRK = 24
FILEMAX = 63 * 1024


def main():
    ok = True
    if open(INC).read() != om.generate():
        print("t_midtab: apps/midirack/mrtab.inc is not what tools/os88midi.py "
              "generates - run `python3 tools/os88midi.py gen` (never edit it "
              "by hand)")
        ok = False
    files = sorted(glob.glob(os.path.join(SONGS, "*.MID")))
    if len(files) != 10:
        print("t_midtab: want the ten shipped songs, found %d" % len(files))
        ok = False
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools",
                                                     "os88midsong.py"),
                        "--check", SONGS], capture_output=True, text=True)
    if r.returncode != 0:
        print("t_midtab: os88midsong.py --check refused the songs:\n" +
              r.stdout + r.stderr)
        ok = False
    theirs = {}
    for line in r.stdout.splitlines():
        m = re.match(r"(\S+\.MID)\s+\d+ B.*?([\d.]+) s", line)
        if m:
            theirs[m.group(1)] = float(m.group(2))
    for f in files:
        name = os.path.basename(f)
        data = open(f, "rb").read()
        try:
            fmt, div, tracks = om.read_smf(data)
            _, secs = om.timeline(data)
        except ValueError as e:
            print("t_midtab: %s: the reference refuses it: %s" % (name, e))
            ok = False
            continue
        if len(data) > FILEMAX or len(tracks) > MAXTRK:
            print("t_midtab: %s is bigger than the player takes" % name)
            ok = False
        if name not in theirs:
            print("t_midtab: %s: the composer's checker printed no length" %
                  name)
            ok = False
        elif abs(theirs[name] - secs) > 0.05:
            print("t_midtab: %s: the two readers disagree - %.3f s against "
                  "%.3f s" % (name, secs, theirs[name]))
            ok = False
    print("t_midtab: %s (%d songs, both readers)" %
          ("ok" if ok else "FAIL", len(files)))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
