#!/usr/bin/env python3
"""PIXELSTEIN 3D's scaler model is what part 2 is sized for, and what the
package's tables say (SPEC.md 97.3).

    python3 tests/unit/t_pxsscale.py

Host-side, soak. tools/pxsgen.py is the byte image of the generated half of
part 2 (the scratch, os88pkg's index) and this row holds it to the package's own numbers: the image of
every backend fits PX_GENKB (pxstein.asm) past the bodies, driver and queue
pxgen.inc puts in front of it; every scaler ends in a near ret and holds a
store for every view row its height covers, once; the directory aliases
every height 1..120 DOWN to a generated one and px_hq in the assembled
part 0 is that same table; px_hts is HEIGHTS; the col2tex widths are at
least 1 (the generator hung on a zero once); and the three layout literals
tests/pxslib.py carries are pxgen.inc's. `t_pxsgen` is the FAST digest row
(a different file, by name), so this one is `t_pxsscale`.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from harness import check, eq, done                         # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "tests"))
import pxsgen                                               # noqa: E402
import os88parts                                            # noqa: E402
import os88build                                            # noqa: E402
from cycweb import pkg_syms                                 # noqa: E402

PXS = os.path.join(ROOT, "apps", "pixelstein")


def equ(path, name):
    src = open(os.path.join(PXS, path)).read()
    m = re.search(r"^%s\s+equ\s+(\d+)" % re.escape(name), src, re.M)
    if not m:
        sys.exit("t_pxsscale: %s has no `%s equ <number>`" % (path, name))
    return int(m.group(1))


def main():
    genkb = equ("pxstein.asm", "PX_GENKB")
    drvmax = equ("pxgen.inc", "PXG_DRVMAX")
    qn = equ("pxgen.inc", "PXG_QN")
    qsz = equ("pxgen.inc", "PXG_QSZ")
    import pxslib
    eq((pxslib.PXG_DRVMAX, pxslib.PXG_QN, pxslib.PXG_QSZ), (drvmax, qn, qsz),
       "tests/pxslib.py's three layout literals are pxgen.inc's")
    syms, image = pkg_syms(os.path.join(PXS, "pxgame.asm"),
                           (os.path.join(ROOT, "apps") + os.sep, PXS + os.sep))
    ball = syms["px_vadj"] - syms["px_bodies"]
    drvsz = syms["px_drv_end"] - syms["px_drv_tpl"]
    check(drvsz <= drvmax, "the driver template (%d bytes) fits PXG_DRVMAX %d" % (drvsz, drvmax))
    scal = ball + drvmax + 6 + qn * qsz         # three header words since wave 3
    print("  t_pxsscale: bodies %d + driver %d + queue %d = PXG_SCAL %d" % (ball, drvmax, 6 + qn * qsz, scal))
    for be, n in sorted(pxsgen.sizes().items()):
        check(scal + n <= genkb * 1024, "%s: %d generated bytes past PXG_SCAL fit %d KB (%d spare)"
              % (be, n, genkb, genkb * 1024 - scal - n))

    hq = list(image[syms["px_hq"]:syms["px_hq"] + 121])
    eq(hq, pxsgen.hq_table(), "px_hq in part 0 is pxsgen.quantise() over 0..120")
    hts = list(image[syms["px_hts"]:syms["px_hts"] + pxsgen.NSC])
    eq(hts, pxsgen.HEIGHTS, "px_hts is pxsgen.HEIGHTS")
    for h in range(1, 200):
        q = pxsgen.quantise(h)
        check(q in pxsgen.HEIGHTS and q <= max(h, 2) and (h > 120 or q <= h),
              "quantise(%d) = %d aliases DOWN to a generated height" % (h, q)) if h % 37 == 0 or h > 118 else None

    for be in ("cga4", "herc", "modex"):
        img, sctab, c2t = pxsgen.image(be, scal)
        ends = 0
        for s in pxsgen.SETS:
            word = s == "low"
            for h in pxsgen.HEIGHTS:
                off = sctab[s][h] - scal
                code = pxsgen.scaler(h, be, word)
                eq(img[off:off + len(code)], code, "%s %s h=%d: the directory points at its scaler" % (be, s, h)) if h in (2, 40, 80, 120) else None
                check(code[-1] == 0xC3, "%s %s h=%d ends in a near ret" % (be, s, h)) if h in (2, 80, 120) else None
                ends += 1
                # a store per covered view row, once
                st = b"\x89\x85" if word else b"\x88\x85"
                rows = sorted(int.from_bytes(code[i + 2:i + 4], "little") // 80
                              for i in range(len(code) - 3) if code[i:i + 2] == st and
                              (i == 0 or code[i - 1] not in (0x26,)))
                want = sorted(r for rs in pxsgen.texel_rows(h) for r in rs)
                if h in (2, 6, 40, 79, 80, 86, 120):
                    eq(rows, want, "%s %s h=%d: one store per view row it covers" % (be, s, h))
            for h in range(121):
                check(sctab[s][h] == sctab[s][pxsgen.quantise(h)], "%s %s: h %d aliases" % (be, s, h)) if h in (1, 3, 81, 85, 119) else None
            # THE codeofs TABLE before each scaler (wave 3, 97.3): 33 words,
            # every non-zero entry the offset of a texel load (0x26 8A 44 v)
            # inside that scaler, non-decreasing, codeofs[32] = 0
            for h in (2, 24, 40, 80, 120):
                base = sctab[s][h]
                cot = [int.from_bytes(img[base - scal - 66 + 2 * v:base - scal - 66 + 2 * v + 2], "little")
                       for v in range(33)]
                code = pxsgen.scaler(h, be, word)
                ok = cot[32] == 0
                last = 0
                for v in range(32):
                    o = cot[v]
                    if o == 0:
                        ok = ok and all(c == 0 for c in cot[v:])
                        break
                    rel = o - base
                    ok = ok and 0 <= rel < len(code) and code[rel] == 0x26 and code[rel + 1] == 0x8A \
                        and code[rel + 3] >= v and o >= last
                    last = o
                check(ok, "%s %s h=%d: codeofs names texel loads at or after v, or 0" % (be, s, h))
        for s in pxsgen.SETS:
            for h in pxsgen.HEIGHTS:
                w = img[c2t[s][h] - scal]
                check(w >= 1, "%s %s h=%d: col2tex width %d >= 1" % (be, s, h, w)) if h in (2, 4, 120) else None
                eq(w, pxsgen.width(h, s == "low"), "%s %s h=%d: the width" % (be, s, h)) if h in (2, 64, 120) else None
        print("  t_pxsscale: %s: %d bytes, %d scalers" % (be, len(img), ends))

    # the shipped package carries this part 0
    try:
        raw = open(os88build.at("build/pxstein.o88"), "rb").read()
        eq(os88parts.part_bytes(raw, 0), image, "build/pxstein.o88's part 0 is the tree's pxgame.asm")
    except OSError:
        print("  t_pxsscale: no build/pxstein.o88 (run make) - the part-0 check skipped")
    done("t_pxsscale")


if __name__ == "__main__":
    main()
