#!/usr/bin/env python3
"""THE SPEAKER SHAPER'S TABLES are the model's (docs/plans/completed/SPEAKER-PCM-PLAN.md).

    python3 tests/unit/t_spkfx.py

apps/os88spkfx_t.inc - the soft clip's curve, the level gains, the
peak-to-level table and the shaper's constants - is GENERATED by
tools/os88spkfx.py, and the gates hold the machine's port writes to that
model's counts. So a hand edit of the include, or a model change nobody
regenerated, would make the machine and its reference disagree while both
still assembled and ran; the Audio and Tracker gates would then fail pointing
at a package. This fails first, naming the file, and runs the model's own
selfcheck (every row inside 1..N-1 and monotonic, a span in pieces equal to
the span whole, silence at a count of 1, the rate plans).

Broken on purpose - a number changed in os88spkfx_t.inc, or SPARSE in the
model - it FAILS.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(
    __file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import os88spkfx as fx      # noqa: E402

INC = os.path.join(ROOT, "apps", "os88spkfx_t.inc")


def main():
    ok = True
    have = open(INC).read()
    if have != fx.gen_inc():
        print("t_spkfx: apps/os88spkfx_t.inc is not what tools/os88spkfx.py "
              "generates - run `python3 tools/os88spkfx.py gen "
              "apps/os88spkfx_t.inc` (and never edit it by hand)")
        ok = False
    ok = fx.selfcheck() and ok
    print("t_spkfx: %s" % ("ok" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
